// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dac_gcmessages_common.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EGCDACCommonMessages int32

const (
	EGCDACCommonMessages_k_EMsgAnyToGCReportAsserts                   EGCDACCommonMessages = 7000
	EGCDACCommonMessages_k_EMsgAnyToGCReportAssertsResponse           EGCDACCommonMessages = 7001
	EGCDACCommonMessages_k_EMsgGCItemEditorReservationsRequest        EGCDACCommonMessages = 7283
	EGCDACCommonMessages_k_EMsgGCItemEditorReservationsResponse       EGCDACCommonMessages = 7284
	EGCDACCommonMessages_k_EMsgGCItemEditorReserveItemDef             EGCDACCommonMessages = 7285
	EGCDACCommonMessages_k_EMsgGCItemEditorReserveItemDefResponse     EGCDACCommonMessages = 7286
	EGCDACCommonMessages_k_EMsgGCItemEditorReleaseReservation         EGCDACCommonMessages = 7287
	EGCDACCommonMessages_k_EMsgGCItemEditorReleaseReservationResponse EGCDACCommonMessages = 7288
)

var EGCDACCommonMessages_name = map[int32]string{
	7000: "k_EMsgAnyToGCReportAsserts",
	7001: "k_EMsgAnyToGCReportAssertsResponse",
	7283: "k_EMsgGCItemEditorReservationsRequest",
	7284: "k_EMsgGCItemEditorReservationsResponse",
	7285: "k_EMsgGCItemEditorReserveItemDef",
	7286: "k_EMsgGCItemEditorReserveItemDefResponse",
	7287: "k_EMsgGCItemEditorReleaseReservation",
	7288: "k_EMsgGCItemEditorReleaseReservationResponse",
}

var EGCDACCommonMessages_value = map[string]int32{
	"k_EMsgAnyToGCReportAsserts":                   7000,
	"k_EMsgAnyToGCReportAssertsResponse":           7001,
	"k_EMsgGCItemEditorReservationsRequest":        7283,
	"k_EMsgGCItemEditorReservationsResponse":       7284,
	"k_EMsgGCItemEditorReserveItemDef":             7285,
	"k_EMsgGCItemEditorReserveItemDefResponse":     7286,
	"k_EMsgGCItemEditorReleaseReservation":         7287,
	"k_EMsgGCItemEditorReleaseReservationResponse": 7288,
}

func (x EGCDACCommonMessages) Enum() *EGCDACCommonMessages {
	p := new(EGCDACCommonMessages)
	*p = x
	return p
}

func (x EGCDACCommonMessages) String() string {
	return proto.EnumName(EGCDACCommonMessages_name, int32(x))
}

func (x *EGCDACCommonMessages) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCDACCommonMessages_value, data, "EGCDACCommonMessages")
	if err != nil {
		return err
	}
	*x = EGCDACCommonMessages(value)
	return nil
}

func (EGCDACCommonMessages) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{0}
}

type EDACMatchMode int32

const (
	EDACMatchMode_k_EDACMatchMode_Invalid      EDACMatchMode = 0
	EDACMatchMode_k_EDACMatchMode_Casual       EDACMatchMode = 1
	EDACMatchMode_k_EDACMatchMode_PrivateLobby EDACMatchMode = 2
	EDACMatchMode_k_EDACMatchMode_SoloBot      EDACMatchMode = 3
	EDACMatchMode_k_EDACMatchMode_Ranked       EDACMatchMode = 4
)

var EDACMatchMode_name = map[int32]string{
	0: "k_EDACMatchMode_Invalid",
	1: "k_EDACMatchMode_Casual",
	2: "k_EDACMatchMode_PrivateLobby",
	3: "k_EDACMatchMode_SoloBot",
	4: "k_EDACMatchMode_Ranked",
}

var EDACMatchMode_value = map[string]int32{
	"k_EDACMatchMode_Invalid":      0,
	"k_EDACMatchMode_Casual":       1,
	"k_EDACMatchMode_PrivateLobby": 2,
	"k_EDACMatchMode_SoloBot":      3,
	"k_EDACMatchMode_Ranked":       4,
}

func (x EDACMatchMode) Enum() *EDACMatchMode {
	p := new(EDACMatchMode)
	*p = x
	return p
}

func (x EDACMatchMode) String() string {
	return proto.EnumName(EDACMatchMode_name, int32(x))
}

func (x *EDACMatchMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDACMatchMode_value, data, "EDACMatchMode")
	if err != nil {
		return err
	}
	*x = EDACMatchMode(value)
	return nil
}

func (EDACMatchMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1}
}

type EDACGameMode int32

const (
	EDACGameMode_k_EDACGameMode_Invalid      EDACGameMode = 0
	EDACGameMode_k_EDACGameMode_Normal       EDACGameMode = 1
	EDACGameMode_k_EDACGameMode_Turbo        EDACGameMode = 2
	EDACGameMode_k_EDACGameMode_BuddyBattles EDACGameMode = 3
)

var EDACGameMode_name = map[int32]string{
	0: "k_EDACGameMode_Invalid",
	1: "k_EDACGameMode_Normal",
	2: "k_EDACGameMode_Turbo",
	3: "k_EDACGameMode_BuddyBattles",
}

var EDACGameMode_value = map[string]int32{
	"k_EDACGameMode_Invalid":      0,
	"k_EDACGameMode_Normal":       1,
	"k_EDACGameMode_Turbo":        2,
	"k_EDACGameMode_BuddyBattles": 3,
}

func (x EDACGameMode) Enum() *EDACGameMode {
	p := new(EDACGameMode)
	*p = x
	return p
}

func (x EDACGameMode) String() string {
	return proto.EnumName(EDACGameMode_name, int32(x))
}

func (x *EDACGameMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDACGameMode_value, data, "EDACGameMode")
	if err != nil {
		return err
	}
	*x = EDACGameMode(value)
	return nil
}

func (EDACGameMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{2}
}

type EDACLobbyTeam int32

const (
	EDACLobbyTeam_k_EDACLobbyTeam_Team0     EDACLobbyTeam = 0
	EDACLobbyTeam_k_EDACLobbyTeam_Team1     EDACLobbyTeam = 1
	EDACLobbyTeam_k_EDACLobbyTeam_Team2     EDACLobbyTeam = 2
	EDACLobbyTeam_k_EDACLobbyTeam_Team3     EDACLobbyTeam = 3
	EDACLobbyTeam_k_EDACLobbyTeam_Team4     EDACLobbyTeam = 4
	EDACLobbyTeam_k_EDACLobbyTeam_Team5     EDACLobbyTeam = 5
	EDACLobbyTeam_k_EDACLobbyTeam_Team6     EDACLobbyTeam = 6
	EDACLobbyTeam_k_EDACLobbyTeam_Team7     EDACLobbyTeam = 7
	EDACLobbyTeam_k_EDACLobbyTeam_Spectator EDACLobbyTeam = 250
)

var EDACLobbyTeam_name = map[int32]string{
	0:   "k_EDACLobbyTeam_Team0",
	1:   "k_EDACLobbyTeam_Team1",
	2:   "k_EDACLobbyTeam_Team2",
	3:   "k_EDACLobbyTeam_Team3",
	4:   "k_EDACLobbyTeam_Team4",
	5:   "k_EDACLobbyTeam_Team5",
	6:   "k_EDACLobbyTeam_Team6",
	7:   "k_EDACLobbyTeam_Team7",
	250: "k_EDACLobbyTeam_Spectator",
}

var EDACLobbyTeam_value = map[string]int32{
	"k_EDACLobbyTeam_Team0":     0,
	"k_EDACLobbyTeam_Team1":     1,
	"k_EDACLobbyTeam_Team2":     2,
	"k_EDACLobbyTeam_Team3":     3,
	"k_EDACLobbyTeam_Team4":     4,
	"k_EDACLobbyTeam_Team5":     5,
	"k_EDACLobbyTeam_Team6":     6,
	"k_EDACLobbyTeam_Team7":     7,
	"k_EDACLobbyTeam_Spectator": 250,
}

func (x EDACLobbyTeam) Enum() *EDACLobbyTeam {
	p := new(EDACLobbyTeam)
	*p = x
	return p
}

func (x EDACLobbyTeam) String() string {
	return proto.EnumName(EDACLobbyTeam_name, int32(x))
}

func (x *EDACLobbyTeam) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDACLobbyTeam_value, data, "EDACLobbyTeam")
	if err != nil {
		return err
	}
	*x = EDACLobbyTeam(value)
	return nil
}

func (EDACLobbyTeam) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{3}
}

type EDACAIType int32

const (
	EDACAIType_k_EDACAIType_Invalid EDACAIType = 0
	EDACAIType_k_EDACAIType_Lvl1    EDACAIType = 1
	EDACAIType_k_EDACAIType_Lvl2    EDACAIType = 2
	EDACAIType_k_EDACAIType_Lvl3    EDACAIType = 3
	EDACAIType_k_EDACAIType_Lvl4    EDACAIType = 4
	EDACAIType_k_EDACAIType_Lvl5    EDACAIType = 5
	EDACAIType_k_EDACAIType_Lvl6    EDACAIType = 6
	EDACAIType_k_EDACAIType_Lvl7    EDACAIType = 7
	EDACAIType_k_EDACAIType_Lvl8    EDACAIType = 8
	EDACAIType_k_EDACAIType_PB0     EDACAIType = 20
	EDACAIType_k_EDACAIType_PB1     EDACAIType = 21
	EDACAIType_k_EDACAIType_PB2     EDACAIType = 22
	EDACAIType_k_EDACAIType_PB3     EDACAIType = 23
	EDACAIType_k_EDACAIType_PB4     EDACAIType = 24
	EDACAIType_k_EDACAIType_PB5     EDACAIType = 25
	EDACAIType_k_EDACAIType_PB6     EDACAIType = 26
	EDACAIType_k_EDACAIType_PB7     EDACAIType = 27
	EDACAIType_k_EDACAIType_PB8     EDACAIType = 28
	EDACAIType_k_EDACAIType_PB9     EDACAIType = 29
	EDACAIType_k_EDACAIType_PB10    EDACAIType = 30
	EDACAIType_k_EDACAIType_PB11    EDACAIType = 31
	EDACAIType_k_EDACAIType_PB12    EDACAIType = 32
	EDACAIType_k_EDACAIType_PB13    EDACAIType = 33
	EDACAIType_k_EDACAIType_PB14    EDACAIType = 34
	EDACAIType_k_EDACAIType_PB15    EDACAIType = 35
	EDACAIType_k_EDACAIType_PB16    EDACAIType = 36
	EDACAIType_k_EDACAIType_PB17    EDACAIType = 37
	EDACAIType_k_EDACAIType_PB18    EDACAIType = 38
	EDACAIType_k_EDACAIType_PB19    EDACAIType = 39
	EDACAIType_k_EDACAIType_PB20    EDACAIType = 40
)

var EDACAIType_name = map[int32]string{
	0:  "k_EDACAIType_Invalid",
	1:  "k_EDACAIType_Lvl1",
	2:  "k_EDACAIType_Lvl2",
	3:  "k_EDACAIType_Lvl3",
	4:  "k_EDACAIType_Lvl4",
	5:  "k_EDACAIType_Lvl5",
	6:  "k_EDACAIType_Lvl6",
	7:  "k_EDACAIType_Lvl7",
	8:  "k_EDACAIType_Lvl8",
	20: "k_EDACAIType_PB0",
	21: "k_EDACAIType_PB1",
	22: "k_EDACAIType_PB2",
	23: "k_EDACAIType_PB3",
	24: "k_EDACAIType_PB4",
	25: "k_EDACAIType_PB5",
	26: "k_EDACAIType_PB6",
	27: "k_EDACAIType_PB7",
	28: "k_EDACAIType_PB8",
	29: "k_EDACAIType_PB9",
	30: "k_EDACAIType_PB10",
	31: "k_EDACAIType_PB11",
	32: "k_EDACAIType_PB12",
	33: "k_EDACAIType_PB13",
	34: "k_EDACAIType_PB14",
	35: "k_EDACAIType_PB15",
	36: "k_EDACAIType_PB16",
	37: "k_EDACAIType_PB17",
	38: "k_EDACAIType_PB18",
	39: "k_EDACAIType_PB19",
	40: "k_EDACAIType_PB20",
}

var EDACAIType_value = map[string]int32{
	"k_EDACAIType_Invalid": 0,
	"k_EDACAIType_Lvl1":    1,
	"k_EDACAIType_Lvl2":    2,
	"k_EDACAIType_Lvl3":    3,
	"k_EDACAIType_Lvl4":    4,
	"k_EDACAIType_Lvl5":    5,
	"k_EDACAIType_Lvl6":    6,
	"k_EDACAIType_Lvl7":    7,
	"k_EDACAIType_Lvl8":    8,
	"k_EDACAIType_PB0":     20,
	"k_EDACAIType_PB1":     21,
	"k_EDACAIType_PB2":     22,
	"k_EDACAIType_PB3":     23,
	"k_EDACAIType_PB4":     24,
	"k_EDACAIType_PB5":     25,
	"k_EDACAIType_PB6":     26,
	"k_EDACAIType_PB7":     27,
	"k_EDACAIType_PB8":     28,
	"k_EDACAIType_PB9":     29,
	"k_EDACAIType_PB10":    30,
	"k_EDACAIType_PB11":    31,
	"k_EDACAIType_PB12":    32,
	"k_EDACAIType_PB13":    33,
	"k_EDACAIType_PB14":    34,
	"k_EDACAIType_PB15":    35,
	"k_EDACAIType_PB16":    36,
	"k_EDACAIType_PB17":    37,
	"k_EDACAIType_PB18":    38,
	"k_EDACAIType_PB19":    39,
	"k_EDACAIType_PB20":    40,
}

func (x EDACAIType) Enum() *EDACAIType {
	p := new(EDACAIType)
	*p = x
	return p
}

func (x EDACAIType) String() string {
	return proto.EnumName(EDACAIType_name, int32(x))
}

func (x *EDACAIType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDACAIType_value, data, "EDACAIType")
	if err != nil {
		return err
	}
	*x = EDACAIType(value)
	return nil
}

func (EDACAIType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4}
}

type EDACMatchState int32

const (
	EDACMatchState_k_EMatchState_InProgress           EDACMatchState = 0
	EDACMatchState_k_EMatchState_Completed            EDACMatchState = 1
	EDACMatchState_k_EMatchState_Failed_NetworkIssues EDACMatchState = 2
	EDACMatchState_k_EMatchState_Failed_ServerCrash   EDACMatchState = 3
)

var EDACMatchState_name = map[int32]string{
	0: "k_EMatchState_InProgress",
	1: "k_EMatchState_Completed",
	2: "k_EMatchState_Failed_NetworkIssues",
	3: "k_EMatchState_Failed_ServerCrash",
}

var EDACMatchState_value = map[string]int32{
	"k_EMatchState_InProgress":           0,
	"k_EMatchState_Completed":            1,
	"k_EMatchState_Failed_NetworkIssues": 2,
	"k_EMatchState_Failed_ServerCrash":   3,
}

func (x EDACMatchState) Enum() *EDACMatchState {
	p := new(EDACMatchState)
	*p = x
	return p
}

func (x EDACMatchState) String() string {
	return proto.EnumName(EDACMatchState_name, int32(x))
}

func (x *EDACMatchState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDACMatchState_value, data, "EDACMatchState")
	if err != nil {
		return err
	}
	*x = EDACMatchState(value)
	return nil
}

func (EDACMatchState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{5}
}

type EDACPlayerState int32

const (
	EDACPlayerState_k_EPlayerState_Playing       EDACPlayerState = 0
	EDACPlayerState_k_EPlayerState_Eliminated    EDACPlayerState = 1
	EDACPlayerState_k_EPlayerState_Abandoned     EDACPlayerState = 2
	EDACPlayerState_k_EPlayerState_Disconnected  EDACPlayerState = 3
	EDACPlayerState_k_EPlayerState_ServerCrashed EDACPlayerState = 4
)

var EDACPlayerState_name = map[int32]string{
	0: "k_EPlayerState_Playing",
	1: "k_EPlayerState_Eliminated",
	2: "k_EPlayerState_Abandoned",
	3: "k_EPlayerState_Disconnected",
	4: "k_EPlayerState_ServerCrashed",
}

var EDACPlayerState_value = map[string]int32{
	"k_EPlayerState_Playing":       0,
	"k_EPlayerState_Eliminated":    1,
	"k_EPlayerState_Abandoned":     2,
	"k_EPlayerState_Disconnected":  3,
	"k_EPlayerState_ServerCrashed": 4,
}

func (x EDACPlayerState) Enum() *EDACPlayerState {
	p := new(EDACPlayerState)
	*p = x
	return p
}

func (x EDACPlayerState) String() string {
	return proto.EnumName(EDACPlayerState_name, int32(x))
}

func (x *EDACPlayerState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDACPlayerState_value, data, "EDACPlayerState")
	if err != nil {
		return err
	}
	*x = EDACPlayerState(value)
	return nil
}

func (EDACPlayerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{6}
}

type ELobbyServerState int32

const (
	ELobbyServerState_k_eLobbyServerState_Assign    ELobbyServerState = 0
	ELobbyServerState_k_eLobbyServerState_InGame    ELobbyServerState = 1
	ELobbyServerState_k_eLobbyServerState_PostMatch ELobbyServerState = 2
	ELobbyServerState_k_eLobbyServerState_SignedOut ELobbyServerState = 3
	ELobbyServerState_k_eLobbyServerState_Abandoned ELobbyServerState = 4
)

var ELobbyServerState_name = map[int32]string{
	0: "k_eLobbyServerState_Assign",
	1: "k_eLobbyServerState_InGame",
	2: "k_eLobbyServerState_PostMatch",
	3: "k_eLobbyServerState_SignedOut",
	4: "k_eLobbyServerState_Abandoned",
}

var ELobbyServerState_value = map[string]int32{
	"k_eLobbyServerState_Assign":    0,
	"k_eLobbyServerState_InGame":    1,
	"k_eLobbyServerState_PostMatch": 2,
	"k_eLobbyServerState_SignedOut": 3,
	"k_eLobbyServerState_Abandoned": 4,
}

func (x ELobbyServerState) Enum() *ELobbyServerState {
	p := new(ELobbyServerState)
	*p = x
	return p
}

func (x ELobbyServerState) String() string {
	return proto.EnumName(ELobbyServerState_name, int32(x))
}

func (x *ELobbyServerState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ELobbyServerState_value, data, "ELobbyServerState")
	if err != nil {
		return err
	}
	*x = ELobbyServerState(value)
	return nil
}

func (ELobbyServerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{7}
}

type CSODACParty_EMemberRights int32

const (
	CSODACParty_k_eMemberRights_Admin        CSODACParty_EMemberRights = 1
	CSODACParty_k_eMemberRights_Creator      CSODACParty_EMemberRights = 2
	CSODACParty_k_eMemberRights_RankedMM     CSODACParty_EMemberRights = 4
	CSODACParty_k_eMemberRights_HighRankedMM CSODACParty_EMemberRights = 8
)

var CSODACParty_EMemberRights_name = map[int32]string{
	1: "k_eMemberRights_Admin",
	2: "k_eMemberRights_Creator",
	4: "k_eMemberRights_RankedMM",
	8: "k_eMemberRights_HighRankedMM",
}

var CSODACParty_EMemberRights_value = map[string]int32{
	"k_eMemberRights_Admin":        1,
	"k_eMemberRights_Creator":      2,
	"k_eMemberRights_RankedMM":     4,
	"k_eMemberRights_HighRankedMM": 8,
}

func (x CSODACParty_EMemberRights) Enum() *CSODACParty_EMemberRights {
	p := new(CSODACParty_EMemberRights)
	*p = x
	return p
}

func (x CSODACParty_EMemberRights) String() string {
	return proto.EnumName(CSODACParty_EMemberRights_name, int32(x))
}

func (x *CSODACParty_EMemberRights) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CSODACParty_EMemberRights_value, data, "CSODACParty_EMemberRights")
	if err != nil {
		return err
	}
	*x = CSODACParty_EMemberRights(value)
	return nil
}

func (CSODACParty_EMemberRights) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4, 0}
}

type CSODACParty_EPlayerType int32

const (
	CSODACParty_k_ePlayerType_Player    CSODACParty_EPlayerType = 0
	CSODACParty_k_ePlayerType_Spectator CSODACParty_EPlayerType = 1
)

var CSODACParty_EPlayerType_name = map[int32]string{
	0: "k_ePlayerType_Player",
	1: "k_ePlayerType_Spectator",
}

var CSODACParty_EPlayerType_value = map[string]int32{
	"k_ePlayerType_Player":    0,
	"k_ePlayerType_Spectator": 1,
}

func (x CSODACParty_EPlayerType) Enum() *CSODACParty_EPlayerType {
	p := new(CSODACParty_EPlayerType)
	*p = x
	return p
}

func (x CSODACParty_EPlayerType) String() string {
	return proto.EnumName(CSODACParty_EPlayerType_name, int32(x))
}

func (x *CSODACParty_EPlayerType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CSODACParty_EPlayerType_value, data, "CSODACParty_EPlayerType")
	if err != nil {
		return err
	}
	*x = CSODACParty_EPlayerType(value)
	return nil
}

func (CSODACParty_EPlayerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4, 1}
}

type CSODACParty_EBotDifficulty int32

const (
	CSODACParty_k_eBotDifficulty_None      CSODACParty_EBotDifficulty = 0
	CSODACParty_k_eBotDifficulty_Easy      CSODACParty_EBotDifficulty = 1
	CSODACParty_k_eBotDifficulty_Medium    CSODACParty_EBotDifficulty = 2
	CSODACParty_k_eBotDifficulty_Hard      CSODACParty_EBotDifficulty = 3
	CSODACParty_k_eBotDifficulty_Nightmare CSODACParty_EBotDifficulty = 4
)

var CSODACParty_EBotDifficulty_name = map[int32]string{
	0: "k_eBotDifficulty_None",
	1: "k_eBotDifficulty_Easy",
	2: "k_eBotDifficulty_Medium",
	3: "k_eBotDifficulty_Hard",
	4: "k_eBotDifficulty_Nightmare",
}

var CSODACParty_EBotDifficulty_value = map[string]int32{
	"k_eBotDifficulty_None":      0,
	"k_eBotDifficulty_Easy":      1,
	"k_eBotDifficulty_Medium":    2,
	"k_eBotDifficulty_Hard":      3,
	"k_eBotDifficulty_Nightmare": 4,
}

func (x CSODACParty_EBotDifficulty) Enum() *CSODACParty_EBotDifficulty {
	p := new(CSODACParty_EBotDifficulty)
	*p = x
	return p
}

func (x CSODACParty_EBotDifficulty) String() string {
	return proto.EnumName(CSODACParty_EBotDifficulty_name, int32(x))
}

func (x *CSODACParty_EBotDifficulty) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CSODACParty_EBotDifficulty_value, data, "CSODACParty_EBotDifficulty")
	if err != nil {
		return err
	}
	*x = CSODACParty_EBotDifficulty(value)
	return nil
}

func (CSODACParty_EBotDifficulty) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4, 2}
}

type CExtraMsgBlock struct {
	MsgType              *uint32  `protobuf:"varint,1,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	Contents             []byte   `protobuf:"bytes,2,opt,name=contents" json:"contents,omitempty"`
	MsgKey               *uint64  `protobuf:"varint,3,opt,name=msg_key,json=msgKey" json:"msg_key,omitempty"`
	IsCompressed         *bool    `protobuf:"varint,4,opt,name=is_compressed,json=isCompressed" json:"is_compressed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CExtraMsgBlock) Reset()         { *m = CExtraMsgBlock{} }
func (m *CExtraMsgBlock) String() string { return proto.CompactTextString(m) }
func (*CExtraMsgBlock) ProtoMessage()    {}
func (*CExtraMsgBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{0}
}

func (m *CExtraMsgBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CExtraMsgBlock.Unmarshal(m, b)
}
func (m *CExtraMsgBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CExtraMsgBlock.Marshal(b, m, deterministic)
}
func (m *CExtraMsgBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CExtraMsgBlock.Merge(m, src)
}
func (m *CExtraMsgBlock) XXX_Size() int {
	return xxx_messageInfo_CExtraMsgBlock.Size(m)
}
func (m *CExtraMsgBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_CExtraMsgBlock.DiscardUnknown(m)
}

var xxx_messageInfo_CExtraMsgBlock proto.InternalMessageInfo

func (m *CExtraMsgBlock) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *CExtraMsgBlock) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *CExtraMsgBlock) GetMsgKey() uint64 {
	if m != nil && m.MsgKey != nil {
		return *m.MsgKey
	}
	return 0
}

func (m *CExtraMsgBlock) GetIsCompressed() bool {
	if m != nil && m.IsCompressed != nil {
		return *m.IsCompressed
	}
	return false
}

type CServerLobbyData_PlayerInfo struct {
	AccountId             *uint32                                    `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	MmrLevel              *uint32                                    `protobuf:"varint,2,opt,name=mmr_level,json=mmrLevel" json:"mmr_level,omitempty"`
	Loadout               []*CServerLobbyData_PlayerInfo_LoadoutSlot `protobuf:"bytes,3,rep,name=loadout" json:"loadout,omitempty"`
	Events                []*CServerLobbyData_PlayerInfo_Event       `protobuf:"bytes,4,rep,name=events" json:"events,omitempty"`
	GlobalLeaderboardRank *uint32                                    `protobuf:"varint,5,opt,name=global_leaderboard_rank,json=globalLeaderboardRank" json:"global_leaderboard_rank,omitempty"`
	Underlord             *uint32                                    `protobuf:"varint,6,opt,name=underlord" json:"underlord,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                   `json:"-"`
	XXX_unrecognized      []byte                                     `json:"-"`
	XXX_sizecache         int32                                      `json:"-"`
}

func (m *CServerLobbyData_PlayerInfo) Reset()         { *m = CServerLobbyData_PlayerInfo{} }
func (m *CServerLobbyData_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CServerLobbyData_PlayerInfo) ProtoMessage()    {}
func (*CServerLobbyData_PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1}
}

func (m *CServerLobbyData_PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo.Unmarshal(m, b)
}
func (m *CServerLobbyData_PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *CServerLobbyData_PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerLobbyData_PlayerInfo.Merge(m, src)
}
func (m *CServerLobbyData_PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo.Size(m)
}
func (m *CServerLobbyData_PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerLobbyData_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CServerLobbyData_PlayerInfo proto.InternalMessageInfo

func (m *CServerLobbyData_PlayerInfo) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo) GetMmrLevel() uint32 {
	if m != nil && m.MmrLevel != nil {
		return *m.MmrLevel
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo) GetLoadout() []*CServerLobbyData_PlayerInfo_LoadoutSlot {
	if m != nil {
		return m.Loadout
	}
	return nil
}

func (m *CServerLobbyData_PlayerInfo) GetEvents() []*CServerLobbyData_PlayerInfo_Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *CServerLobbyData_PlayerInfo) GetGlobalLeaderboardRank() uint32 {
	if m != nil && m.GlobalLeaderboardRank != nil {
		return *m.GlobalLeaderboardRank
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo) GetUnderlord() uint32 {
	if m != nil && m.Underlord != nil {
		return *m.Underlord
	}
	return 0
}

type CServerLobbyData_PlayerInfo_LoadoutSlot struct {
	LoadoutSlot          *uint32  `protobuf:"varint,1,opt,name=loadout_slot,json=loadoutSlot" json:"loadout_slot,omitempty"`
	DefIndex             *uint32  `protobuf:"varint,2,opt,name=def_index,json=defIndex" json:"def_index,omitempty"`
	LoadoutSubSlot       *uint32  `protobuf:"varint,3,opt,name=loadout_sub_slot,json=loadoutSubSlot" json:"loadout_sub_slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) Reset() {
	*m = CServerLobbyData_PlayerInfo_LoadoutSlot{}
}
func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) String() string { return proto.CompactTextString(m) }
func (*CServerLobbyData_PlayerInfo_LoadoutSlot) ProtoMessage()    {}
func (*CServerLobbyData_PlayerInfo_LoadoutSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1, 0}
}

func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_LoadoutSlot.Unmarshal(m, b)
}
func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_LoadoutSlot.Marshal(b, m, deterministic)
}
func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_LoadoutSlot.Merge(m, src)
}
func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) XXX_Size() int {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_LoadoutSlot.Size(m)
}
func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_LoadoutSlot.DiscardUnknown(m)
}

var xxx_messageInfo_CServerLobbyData_PlayerInfo_LoadoutSlot proto.InternalMessageInfo

func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) GetLoadoutSlot() uint32 {
	if m != nil && m.LoadoutSlot != nil {
		return *m.LoadoutSlot
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) GetDefIndex() uint32 {
	if m != nil && m.DefIndex != nil {
		return *m.DefIndex
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_LoadoutSlot) GetLoadoutSubSlot() uint32 {
	if m != nil && m.LoadoutSubSlot != nil {
		return *m.LoadoutSubSlot
	}
	return 0
}

type CServerLobbyData_PlayerInfo_Currency struct {
	CurrencyId           *uint32  `protobuf:"varint,1,opt,name=currency_id,json=currencyId" json:"currency_id,omitempty"`
	Amount               *uint32  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CServerLobbyData_PlayerInfo_Currency) Reset()         { *m = CServerLobbyData_PlayerInfo_Currency{} }
func (m *CServerLobbyData_PlayerInfo_Currency) String() string { return proto.CompactTextString(m) }
func (*CServerLobbyData_PlayerInfo_Currency) ProtoMessage()    {}
func (*CServerLobbyData_PlayerInfo_Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1, 1}
}

func (m *CServerLobbyData_PlayerInfo_Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Currency.Unmarshal(m, b)
}
func (m *CServerLobbyData_PlayerInfo_Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Currency.Marshal(b, m, deterministic)
}
func (m *CServerLobbyData_PlayerInfo_Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_Currency.Merge(m, src)
}
func (m *CServerLobbyData_PlayerInfo_Currency) XXX_Size() int {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Currency.Size(m)
}
func (m *CServerLobbyData_PlayerInfo_Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_CServerLobbyData_PlayerInfo_Currency proto.InternalMessageInfo

func (m *CServerLobbyData_PlayerInfo_Currency) GetCurrencyId() uint32 {
	if m != nil && m.CurrencyId != nil {
		return *m.CurrencyId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Currency) GetAmount() uint32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type CServerLobbyData_PlayerInfo_Challenge struct {
	ChallengeId          *uint32  `protobuf:"varint,1,opt,name=challenge_id,json=challengeId" json:"challenge_id,omitempty"`
	Progress             *uint32  `protobuf:"varint,2,opt,name=progress" json:"progress,omitempty"`
	SequenceId           *uint32  `protobuf:"varint,3,opt,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	SlotId               *uint32  `protobuf:"varint,4,opt,name=slot_id,json=slotId" json:"slot_id,omitempty"`
	ConfigId             *uint32  `protobuf:"varint,5,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Claimed              *uint32  `protobuf:"varint,6,opt,name=claimed" json:"claimed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CServerLobbyData_PlayerInfo_Challenge) Reset()         { *m = CServerLobbyData_PlayerInfo_Challenge{} }
func (m *CServerLobbyData_PlayerInfo_Challenge) String() string { return proto.CompactTextString(m) }
func (*CServerLobbyData_PlayerInfo_Challenge) ProtoMessage()    {}
func (*CServerLobbyData_PlayerInfo_Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1, 2}
}

func (m *CServerLobbyData_PlayerInfo_Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Challenge.Unmarshal(m, b)
}
func (m *CServerLobbyData_PlayerInfo_Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Challenge.Marshal(b, m, deterministic)
}
func (m *CServerLobbyData_PlayerInfo_Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_Challenge.Merge(m, src)
}
func (m *CServerLobbyData_PlayerInfo_Challenge) XXX_Size() int {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Challenge.Size(m)
}
func (m *CServerLobbyData_PlayerInfo_Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_CServerLobbyData_PlayerInfo_Challenge proto.InternalMessageInfo

func (m *CServerLobbyData_PlayerInfo_Challenge) GetChallengeId() uint32 {
	if m != nil && m.ChallengeId != nil {
		return *m.ChallengeId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Challenge) GetProgress() uint32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Challenge) GetSequenceId() uint32 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Challenge) GetSlotId() uint32 {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Challenge) GetConfigId() uint32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Challenge) GetClaimed() uint32 {
	if m != nil && m.Claimed != nil {
		return *m.Claimed
	}
	return 0
}

type CServerLobbyData_PlayerInfo_VirtualItem struct {
	DefIndex             *uint32  `protobuf:"varint,1,opt,name=def_index,json=defIndex" json:"def_index,omitempty"`
	EquipSlot            *uint32  `protobuf:"varint,2,opt,name=equip_slot,json=equipSlot" json:"equip_slot,omitempty"`
	EquipSubSlot         *uint32  `protobuf:"varint,3,opt,name=equip_sub_slot,json=equipSubSlot" json:"equip_sub_slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CServerLobbyData_PlayerInfo_VirtualItem) Reset() {
	*m = CServerLobbyData_PlayerInfo_VirtualItem{}
}
func (m *CServerLobbyData_PlayerInfo_VirtualItem) String() string { return proto.CompactTextString(m) }
func (*CServerLobbyData_PlayerInfo_VirtualItem) ProtoMessage()    {}
func (*CServerLobbyData_PlayerInfo_VirtualItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1, 3}
}

func (m *CServerLobbyData_PlayerInfo_VirtualItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_VirtualItem.Unmarshal(m, b)
}
func (m *CServerLobbyData_PlayerInfo_VirtualItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_VirtualItem.Marshal(b, m, deterministic)
}
func (m *CServerLobbyData_PlayerInfo_VirtualItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_VirtualItem.Merge(m, src)
}
func (m *CServerLobbyData_PlayerInfo_VirtualItem) XXX_Size() int {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_VirtualItem.Size(m)
}
func (m *CServerLobbyData_PlayerInfo_VirtualItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_VirtualItem.DiscardUnknown(m)
}

var xxx_messageInfo_CServerLobbyData_PlayerInfo_VirtualItem proto.InternalMessageInfo

func (m *CServerLobbyData_PlayerInfo_VirtualItem) GetDefIndex() uint32 {
	if m != nil && m.DefIndex != nil {
		return *m.DefIndex
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_VirtualItem) GetEquipSlot() uint32 {
	if m != nil && m.EquipSlot != nil {
		return *m.EquipSlot
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_VirtualItem) GetEquipSubSlot() uint32 {
	if m != nil && m.EquipSubSlot != nil {
		return *m.EquipSubSlot
	}
	return 0
}

type CServerLobbyData_PlayerInfo_Event struct {
	EventId              *uint32                                    `protobuf:"varint,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	EventOwned           *bool                                      `protobuf:"varint,2,opt,name=event_owned,json=eventOwned" json:"event_owned,omitempty"`
	Challenges           []*CServerLobbyData_PlayerInfo_Challenge   `protobuf:"bytes,3,rep,name=challenges" json:"challenges,omitempty"`
	Currencies           []*CServerLobbyData_PlayerInfo_Currency    `protobuf:"bytes,4,rep,name=currencies" json:"currencies,omitempty"`
	VirtualItems         []*CServerLobbyData_PlayerInfo_VirtualItem `protobuf:"bytes,5,rep,name=virtual_items,json=virtualItems" json:"virtual_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *CServerLobbyData_PlayerInfo_Event) Reset()         { *m = CServerLobbyData_PlayerInfo_Event{} }
func (m *CServerLobbyData_PlayerInfo_Event) String() string { return proto.CompactTextString(m) }
func (*CServerLobbyData_PlayerInfo_Event) ProtoMessage()    {}
func (*CServerLobbyData_PlayerInfo_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{1, 4}
}

func (m *CServerLobbyData_PlayerInfo_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Event.Unmarshal(m, b)
}
func (m *CServerLobbyData_PlayerInfo_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Event.Marshal(b, m, deterministic)
}
func (m *CServerLobbyData_PlayerInfo_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_Event.Merge(m, src)
}
func (m *CServerLobbyData_PlayerInfo_Event) XXX_Size() int {
	return xxx_messageInfo_CServerLobbyData_PlayerInfo_Event.Size(m)
}
func (m *CServerLobbyData_PlayerInfo_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerLobbyData_PlayerInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_CServerLobbyData_PlayerInfo_Event proto.InternalMessageInfo

func (m *CServerLobbyData_PlayerInfo_Event) GetEventId() uint32 {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return 0
}

func (m *CServerLobbyData_PlayerInfo_Event) GetEventOwned() bool {
	if m != nil && m.EventOwned != nil {
		return *m.EventOwned
	}
	return false
}

func (m *CServerLobbyData_PlayerInfo_Event) GetChallenges() []*CServerLobbyData_PlayerInfo_Challenge {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *CServerLobbyData_PlayerInfo_Event) GetCurrencies() []*CServerLobbyData_PlayerInfo_Currency {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *CServerLobbyData_PlayerInfo_Event) GetVirtualItems() []*CServerLobbyData_PlayerInfo_VirtualItem {
	if m != nil {
		return m.VirtualItems
	}
	return nil
}

type CMsgRegionPingTimesClient struct {
	DataCenterCodes      []uint32 `protobuf:"fixed32,1,rep,packed,name=data_center_codes,json=dataCenterCodes" json:"data_center_codes,omitempty"`
	PingTimes            []uint32 `protobuf:"varint,2,rep,packed,name=ping_times,json=pingTimes" json:"ping_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgRegionPingTimesClient) Reset()         { *m = CMsgRegionPingTimesClient{} }
func (m *CMsgRegionPingTimesClient) String() string { return proto.CompactTextString(m) }
func (*CMsgRegionPingTimesClient) ProtoMessage()    {}
func (*CMsgRegionPingTimesClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{2}
}

func (m *CMsgRegionPingTimesClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgRegionPingTimesClient.Unmarshal(m, b)
}
func (m *CMsgRegionPingTimesClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgRegionPingTimesClient.Marshal(b, m, deterministic)
}
func (m *CMsgRegionPingTimesClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgRegionPingTimesClient.Merge(m, src)
}
func (m *CMsgRegionPingTimesClient) XXX_Size() int {
	return xxx_messageInfo_CMsgRegionPingTimesClient.Size(m)
}
func (m *CMsgRegionPingTimesClient) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgRegionPingTimesClient.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgRegionPingTimesClient proto.InternalMessageInfo

func (m *CMsgRegionPingTimesClient) GetDataCenterCodes() []uint32 {
	if m != nil {
		return m.DataCenterCodes
	}
	return nil
}

func (m *CMsgRegionPingTimesClient) GetPingTimes() []uint32 {
	if m != nil {
		return m.PingTimes
	}
	return nil
}

type CSODACLobby struct {
	ServerVersion        *uint32            `protobuf:"varint,1,opt,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	CompatibilityVersion *uint32            `protobuf:"varint,2,opt,name=compatibility_version,json=compatibilityVersion" json:"compatibility_version,omitempty"`
	ServerSteamId        *uint64            `protobuf:"fixed64,3,opt,name=server_steam_id,json=serverSteamId" json:"server_steam_id,omitempty"`
	LobbyId              *uint64            `protobuf:"varint,5,opt,name=lobby_id,json=lobbyId" json:"lobby_id,omitempty"`
	MatchId              *uint64            `protobuf:"varint,6,opt,name=match_id,json=matchId" json:"match_id,omitempty"`
	ServerState          *ELobbyServerState `protobuf:"varint,8,opt,name=server_state,json=serverState,enum=protocol.ELobbyServerState,def=0" json:"server_state,omitempty"`
	MatchMode            *EDACMatchMode     `protobuf:"varint,10,opt,name=match_mode,json=matchMode,enum=protocol.EDACMatchMode,def=0" json:"match_mode,omitempty"`
	UdpConnectIp         *uint32            `protobuf:"varint,11,opt,name=udp_connect_ip,json=udpConnectIp" json:"udp_connect_ip,omitempty"`
	UdpConnectPort       *uint32            `protobuf:"varint,12,opt,name=udp_connect_port,json=udpConnectPort" json:"udp_connect_port,omitempty"`
	GameMode             *EDACGameMode      `protobuf:"varint,13,opt,name=game_mode,json=gameMode,enum=protocol.EDACGameMode,def=0" json:"game_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CSODACLobby) Reset()         { *m = CSODACLobby{} }
func (m *CSODACLobby) String() string { return proto.CompactTextString(m) }
func (*CSODACLobby) ProtoMessage()    {}
func (*CSODACLobby) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{3}
}

func (m *CSODACLobby) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSODACLobby.Unmarshal(m, b)
}
func (m *CSODACLobby) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSODACLobby.Marshal(b, m, deterministic)
}
func (m *CSODACLobby) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSODACLobby.Merge(m, src)
}
func (m *CSODACLobby) XXX_Size() int {
	return xxx_messageInfo_CSODACLobby.Size(m)
}
func (m *CSODACLobby) XXX_DiscardUnknown() {
	xxx_messageInfo_CSODACLobby.DiscardUnknown(m)
}

var xxx_messageInfo_CSODACLobby proto.InternalMessageInfo

const Default_CSODACLobby_ServerState ELobbyServerState = ELobbyServerState_k_eLobbyServerState_Assign
const Default_CSODACLobby_MatchMode EDACMatchMode = EDACMatchMode_k_EDACMatchMode_Invalid
const Default_CSODACLobby_GameMode EDACGameMode = EDACGameMode_k_EDACGameMode_Invalid

func (m *CSODACLobby) GetServerVersion() uint32 {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return 0
}

func (m *CSODACLobby) GetCompatibilityVersion() uint32 {
	if m != nil && m.CompatibilityVersion != nil {
		return *m.CompatibilityVersion
	}
	return 0
}

func (m *CSODACLobby) GetServerSteamId() uint64 {
	if m != nil && m.ServerSteamId != nil {
		return *m.ServerSteamId
	}
	return 0
}

func (m *CSODACLobby) GetLobbyId() uint64 {
	if m != nil && m.LobbyId != nil {
		return *m.LobbyId
	}
	return 0
}

func (m *CSODACLobby) GetMatchId() uint64 {
	if m != nil && m.MatchId != nil {
		return *m.MatchId
	}
	return 0
}

func (m *CSODACLobby) GetServerState() ELobbyServerState {
	if m != nil && m.ServerState != nil {
		return *m.ServerState
	}
	return Default_CSODACLobby_ServerState
}

func (m *CSODACLobby) GetMatchMode() EDACMatchMode {
	if m != nil && m.MatchMode != nil {
		return *m.MatchMode
	}
	return Default_CSODACLobby_MatchMode
}

func (m *CSODACLobby) GetUdpConnectIp() uint32 {
	if m != nil && m.UdpConnectIp != nil {
		return *m.UdpConnectIp
	}
	return 0
}

func (m *CSODACLobby) GetUdpConnectPort() uint32 {
	if m != nil && m.UdpConnectPort != nil {
		return *m.UdpConnectPort
	}
	return 0
}

func (m *CSODACLobby) GetGameMode() EDACGameMode {
	if m != nil && m.GameMode != nil {
		return *m.GameMode
	}
	return Default_CSODACLobby_GameMode
}

type CSODACParty struct {
	PartyId              *uint64                     `protobuf:"varint,1,opt,name=party_id,json=partyId" json:"party_id,omitempty"`
	Members              []*CSODACParty_Member       `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	Invites              []*CSODACParty_Invite       `protobuf:"bytes,3,rep,name=invites" json:"invites,omitempty"`
	InMatchMaking        *bool                       `protobuf:"varint,5,opt,name=in_match_making,json=inMatchMaking" json:"in_match_making,omitempty"`
	PartyPassword        *string                     `protobuf:"bytes,6,opt,name=party_password,json=partyPassword" json:"party_password,omitempty"`
	LeftMembers          []*CSODACParty_LeftMember   `protobuf:"bytes,10,rep,name=left_members,json=leftMembers" json:"left_members,omitempty"`
	JoinCode             *uint64                     `protobuf:"varint,11,opt,name=join_code,json=joinCode" json:"join_code,omitempty"`
	BotDifficulty        *CSODACParty_EBotDifficulty `protobuf:"varint,12,opt,name=bot_difficulty,json=botDifficulty,enum=protocol.CSODACParty_EBotDifficulty,def=0" json:"bot_difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CSODACParty) Reset()         { *m = CSODACParty{} }
func (m *CSODACParty) String() string { return proto.CompactTextString(m) }
func (*CSODACParty) ProtoMessage()    {}
func (*CSODACParty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4}
}

func (m *CSODACParty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSODACParty.Unmarshal(m, b)
}
func (m *CSODACParty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSODACParty.Marshal(b, m, deterministic)
}
func (m *CSODACParty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSODACParty.Merge(m, src)
}
func (m *CSODACParty) XXX_Size() int {
	return xxx_messageInfo_CSODACParty.Size(m)
}
func (m *CSODACParty) XXX_DiscardUnknown() {
	xxx_messageInfo_CSODACParty.DiscardUnknown(m)
}

var xxx_messageInfo_CSODACParty proto.InternalMessageInfo

const Default_CSODACParty_BotDifficulty CSODACParty_EBotDifficulty = CSODACParty_k_eBotDifficulty_None

func (m *CSODACParty) GetPartyId() uint64 {
	if m != nil && m.PartyId != nil {
		return *m.PartyId
	}
	return 0
}

func (m *CSODACParty) GetMembers() []*CSODACParty_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CSODACParty) GetInvites() []*CSODACParty_Invite {
	if m != nil {
		return m.Invites
	}
	return nil
}

func (m *CSODACParty) GetInMatchMaking() bool {
	if m != nil && m.InMatchMaking != nil {
		return *m.InMatchMaking
	}
	return false
}

func (m *CSODACParty) GetPartyPassword() string {
	if m != nil && m.PartyPassword != nil {
		return *m.PartyPassword
	}
	return ""
}

func (m *CSODACParty) GetLeftMembers() []*CSODACParty_LeftMember {
	if m != nil {
		return m.LeftMembers
	}
	return nil
}

func (m *CSODACParty) GetJoinCode() uint64 {
	if m != nil && m.JoinCode != nil {
		return *m.JoinCode
	}
	return 0
}

func (m *CSODACParty) GetBotDifficulty() CSODACParty_EBotDifficulty {
	if m != nil && m.BotDifficulty != nil {
		return *m.BotDifficulty
	}
	return Default_CSODACParty_BotDifficulty
}

type CSODACParty_Member struct {
	AccountId            *uint32                  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	PersonaName          *string                  `protobuf:"bytes,2,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	RightsFlags          *uint32                  `protobuf:"varint,3,opt,name=rights_flags,json=rightsFlags" json:"rights_flags,omitempty"`
	IsReady              *bool                    `protobuf:"varint,4,opt,name=is_ready,json=isReady" json:"is_ready,omitempty"`
	PlayerType           *CSODACParty_EPlayerType `protobuf:"varint,5,opt,name=player_type,json=playerType,enum=protocol.CSODACParty_EPlayerType,def=0" json:"player_type,omitempty"`
	CompatibilityVersion *uint32                  `protobuf:"varint,6,opt,name=compatibility_version,json=compatibilityVersion" json:"compatibility_version,omitempty"`
	Platform             *EDACPlatform            `protobuf:"varint,7,opt,name=platform,enum=protocol.EDACPlatform,def=0" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CSODACParty_Member) Reset()         { *m = CSODACParty_Member{} }
func (m *CSODACParty_Member) String() string { return proto.CompactTextString(m) }
func (*CSODACParty_Member) ProtoMessage()    {}
func (*CSODACParty_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4, 0}
}

func (m *CSODACParty_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSODACParty_Member.Unmarshal(m, b)
}
func (m *CSODACParty_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSODACParty_Member.Marshal(b, m, deterministic)
}
func (m *CSODACParty_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSODACParty_Member.Merge(m, src)
}
func (m *CSODACParty_Member) XXX_Size() int {
	return xxx_messageInfo_CSODACParty_Member.Size(m)
}
func (m *CSODACParty_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_CSODACParty_Member.DiscardUnknown(m)
}

var xxx_messageInfo_CSODACParty_Member proto.InternalMessageInfo

const Default_CSODACParty_Member_PlayerType CSODACParty_EPlayerType = CSODACParty_k_ePlayerType_Player
const Default_CSODACParty_Member_Platform EDACPlatform = EDACPlatform_k_eDACPlatform_None

func (m *CSODACParty_Member) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CSODACParty_Member) GetPersonaName() string {
	if m != nil && m.PersonaName != nil {
		return *m.PersonaName
	}
	return ""
}

func (m *CSODACParty_Member) GetRightsFlags() uint32 {
	if m != nil && m.RightsFlags != nil {
		return *m.RightsFlags
	}
	return 0
}

func (m *CSODACParty_Member) GetIsReady() bool {
	if m != nil && m.IsReady != nil {
		return *m.IsReady
	}
	return false
}

func (m *CSODACParty_Member) GetPlayerType() CSODACParty_EPlayerType {
	if m != nil && m.PlayerType != nil {
		return *m.PlayerType
	}
	return Default_CSODACParty_Member_PlayerType
}

func (m *CSODACParty_Member) GetCompatibilityVersion() uint32 {
	if m != nil && m.CompatibilityVersion != nil {
		return *m.CompatibilityVersion
	}
	return 0
}

func (m *CSODACParty_Member) GetPlatform() EDACPlatform {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Default_CSODACParty_Member_Platform
}

type CSODACParty_LeftMember struct {
	AccountId            *uint32                  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	RightsFlags          *uint32                  `protobuf:"varint,2,opt,name=rights_flags,json=rightsFlags" json:"rights_flags,omitempty"`
	PlayerType           *CSODACParty_EPlayerType `protobuf:"varint,3,opt,name=player_type,json=playerType,enum=protocol.CSODACParty_EPlayerType,def=0" json:"player_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CSODACParty_LeftMember) Reset()         { *m = CSODACParty_LeftMember{} }
func (m *CSODACParty_LeftMember) String() string { return proto.CompactTextString(m) }
func (*CSODACParty_LeftMember) ProtoMessage()    {}
func (*CSODACParty_LeftMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4, 1}
}

func (m *CSODACParty_LeftMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSODACParty_LeftMember.Unmarshal(m, b)
}
func (m *CSODACParty_LeftMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSODACParty_LeftMember.Marshal(b, m, deterministic)
}
func (m *CSODACParty_LeftMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSODACParty_LeftMember.Merge(m, src)
}
func (m *CSODACParty_LeftMember) XXX_Size() int {
	return xxx_messageInfo_CSODACParty_LeftMember.Size(m)
}
func (m *CSODACParty_LeftMember) XXX_DiscardUnknown() {
	xxx_messageInfo_CSODACParty_LeftMember.DiscardUnknown(m)
}

var xxx_messageInfo_CSODACParty_LeftMember proto.InternalMessageInfo

const Default_CSODACParty_LeftMember_PlayerType CSODACParty_EPlayerType = CSODACParty_k_ePlayerType_Player

func (m *CSODACParty_LeftMember) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CSODACParty_LeftMember) GetRightsFlags() uint32 {
	if m != nil && m.RightsFlags != nil {
		return *m.RightsFlags
	}
	return 0
}

func (m *CSODACParty_LeftMember) GetPlayerType() CSODACParty_EPlayerType {
	if m != nil && m.PlayerType != nil {
		return *m.PlayerType
	}
	return Default_CSODACParty_LeftMember_PlayerType
}

type CSODACParty_Invite struct {
	AccountId            *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	PersonaName          *string  `protobuf:"bytes,2,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	InvitedBy            *uint32  `protobuf:"varint,3,opt,name=invited_by,json=invitedBy" json:"invited_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSODACParty_Invite) Reset()         { *m = CSODACParty_Invite{} }
func (m *CSODACParty_Invite) String() string { return proto.CompactTextString(m) }
func (*CSODACParty_Invite) ProtoMessage()    {}
func (*CSODACParty_Invite) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{4, 2}
}

func (m *CSODACParty_Invite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSODACParty_Invite.Unmarshal(m, b)
}
func (m *CSODACParty_Invite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSODACParty_Invite.Marshal(b, m, deterministic)
}
func (m *CSODACParty_Invite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSODACParty_Invite.Merge(m, src)
}
func (m *CSODACParty_Invite) XXX_Size() int {
	return xxx_messageInfo_CSODACParty_Invite.Size(m)
}
func (m *CSODACParty_Invite) XXX_DiscardUnknown() {
	xxx_messageInfo_CSODACParty_Invite.DiscardUnknown(m)
}

var xxx_messageInfo_CSODACParty_Invite proto.InternalMessageInfo

func (m *CSODACParty_Invite) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CSODACParty_Invite) GetPersonaName() string {
	if m != nil && m.PersonaName != nil {
		return *m.PersonaName
	}
	return ""
}

func (m *CSODACParty_Invite) GetInvitedBy() uint32 {
	if m != nil && m.InvitedBy != nil {
		return *m.InvitedBy
	}
	return 0
}

type CSOGameAccountClient struct {
	AccountId               *uint32  `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	MmrLevel                *uint32  `protobuf:"varint,2,opt,name=mmr_level,json=mmrLevel" json:"mmr_level,omitempty"`
	MmrLeaderboard          *uint32  `protobuf:"varint,3,opt,name=mmr_leaderboard,json=mmrLeaderboard" json:"mmr_leaderboard,omitempty"`
	Flags                   *uint64  `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	UnlockRankedProgress    *uint32  `protobuf:"varint,5,opt,name=unlock_ranked_progress,json=unlockRankedProgress" json:"unlock_ranked_progress,omitempty"`
	ActiveUnderlord         *uint32  `protobuf:"varint,7,opt,name=active_underlord,json=activeUnderlord" json:"active_underlord,omitempty"`
	MmrLevelPartialProgress *float32 `protobuf:"fixed32,6,opt,name=mmr_level_partial_progress,json=mmrLevelPartialProgress" json:"mmr_level_partial_progress,omitempty"`
	MmrLevelScore           *uint32  `protobuf:"varint,8,opt,name=mmr_level_score,json=mmrLevelScore" json:"mmr_level_score,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *CSOGameAccountClient) Reset()         { *m = CSOGameAccountClient{} }
func (m *CSOGameAccountClient) String() string { return proto.CompactTextString(m) }
func (*CSOGameAccountClient) ProtoMessage()    {}
func (*CSOGameAccountClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{5}
}

func (m *CSOGameAccountClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSOGameAccountClient.Unmarshal(m, b)
}
func (m *CSOGameAccountClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSOGameAccountClient.Marshal(b, m, deterministic)
}
func (m *CSOGameAccountClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSOGameAccountClient.Merge(m, src)
}
func (m *CSOGameAccountClient) XXX_Size() int {
	return xxx_messageInfo_CSOGameAccountClient.Size(m)
}
func (m *CSOGameAccountClient) XXX_DiscardUnknown() {
	xxx_messageInfo_CSOGameAccountClient.DiscardUnknown(m)
}

var xxx_messageInfo_CSOGameAccountClient proto.InternalMessageInfo

func (m *CSOGameAccountClient) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CSOGameAccountClient) GetMmrLevel() uint32 {
	if m != nil && m.MmrLevel != nil {
		return *m.MmrLevel
	}
	return 0
}

func (m *CSOGameAccountClient) GetMmrLeaderboard() uint32 {
	if m != nil && m.MmrLeaderboard != nil {
		return *m.MmrLeaderboard
	}
	return 0
}

func (m *CSOGameAccountClient) GetFlags() uint64 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CSOGameAccountClient) GetUnlockRankedProgress() uint32 {
	if m != nil && m.UnlockRankedProgress != nil {
		return *m.UnlockRankedProgress
	}
	return 0
}

func (m *CSOGameAccountClient) GetActiveUnderlord() uint32 {
	if m != nil && m.ActiveUnderlord != nil {
		return *m.ActiveUnderlord
	}
	return 0
}

func (m *CSOGameAccountClient) GetMmrLevelPartialProgress() float32 {
	if m != nil && m.MmrLevelPartialProgress != nil {
		return *m.MmrLevelPartialProgress
	}
	return 0
}

func (m *CSOGameAccountClient) GetMmrLevelScore() uint32 {
	if m != nil && m.MmrLevelScore != nil {
		return *m.MmrLevelScore
	}
	return 0
}

type CMsgStartFindingMatchInfo struct {
	ClientVersion        *uint32                     `protobuf:"varint,2,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	MatchMode            *EDACMatchMode              `protobuf:"varint,3,opt,name=match_mode,json=matchMode,enum=protocol.EDACMatchMode,def=0" json:"match_mode,omitempty"`
	Platform             *EDACPlatform               `protobuf:"varint,4,opt,name=platform,enum=protocol.EDACPlatform,def=0" json:"platform,omitempty"`
	BotDifficulty        *CSODACParty_EBotDifficulty `protobuf:"varint,5,opt,name=bot_difficulty,json=botDifficulty,enum=protocol.CSODACParty_EBotDifficulty,def=0" json:"bot_difficulty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CMsgStartFindingMatchInfo) Reset()         { *m = CMsgStartFindingMatchInfo{} }
func (m *CMsgStartFindingMatchInfo) String() string { return proto.CompactTextString(m) }
func (*CMsgStartFindingMatchInfo) ProtoMessage()    {}
func (*CMsgStartFindingMatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{6}
}

func (m *CMsgStartFindingMatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgStartFindingMatchInfo.Unmarshal(m, b)
}
func (m *CMsgStartFindingMatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgStartFindingMatchInfo.Marshal(b, m, deterministic)
}
func (m *CMsgStartFindingMatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgStartFindingMatchInfo.Merge(m, src)
}
func (m *CMsgStartFindingMatchInfo) XXX_Size() int {
	return xxx_messageInfo_CMsgStartFindingMatchInfo.Size(m)
}
func (m *CMsgStartFindingMatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgStartFindingMatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgStartFindingMatchInfo proto.InternalMessageInfo

const Default_CMsgStartFindingMatchInfo_MatchMode EDACMatchMode = EDACMatchMode_k_EDACMatchMode_Invalid
const Default_CMsgStartFindingMatchInfo_Platform EDACPlatform = EDACPlatform_k_eDACPlatform_None
const Default_CMsgStartFindingMatchInfo_BotDifficulty CSODACParty_EBotDifficulty = CSODACParty_k_eBotDifficulty_None

func (m *CMsgStartFindingMatchInfo) GetClientVersion() uint32 {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return 0
}

func (m *CMsgStartFindingMatchInfo) GetMatchMode() EDACMatchMode {
	if m != nil && m.MatchMode != nil {
		return *m.MatchMode
	}
	return Default_CMsgStartFindingMatchInfo_MatchMode
}

func (m *CMsgStartFindingMatchInfo) GetPlatform() EDACPlatform {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return Default_CMsgStartFindingMatchInfo_Platform
}

func (m *CMsgStartFindingMatchInfo) GetBotDifficulty() CSODACParty_EBotDifficulty {
	if m != nil && m.BotDifficulty != nil {
		return *m.BotDifficulty
	}
	return Default_CMsgStartFindingMatchInfo_BotDifficulty
}

type CMsgAnyToGCReportAsserts struct {
	Version              *uint32                                   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Asserts              []*CMsgAnyToGCReportAsserts_TrackedAssert `protobuf:"bytes,2,rep,name=asserts" json:"asserts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *CMsgAnyToGCReportAsserts) Reset()         { *m = CMsgAnyToGCReportAsserts{} }
func (m *CMsgAnyToGCReportAsserts) String() string { return proto.CompactTextString(m) }
func (*CMsgAnyToGCReportAsserts) ProtoMessage()    {}
func (*CMsgAnyToGCReportAsserts) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{7}
}

func (m *CMsgAnyToGCReportAsserts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgAnyToGCReportAsserts.Unmarshal(m, b)
}
func (m *CMsgAnyToGCReportAsserts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgAnyToGCReportAsserts.Marshal(b, m, deterministic)
}
func (m *CMsgAnyToGCReportAsserts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgAnyToGCReportAsserts.Merge(m, src)
}
func (m *CMsgAnyToGCReportAsserts) XXX_Size() int {
	return xxx_messageInfo_CMsgAnyToGCReportAsserts.Size(m)
}
func (m *CMsgAnyToGCReportAsserts) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgAnyToGCReportAsserts.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgAnyToGCReportAsserts proto.InternalMessageInfo

func (m *CMsgAnyToGCReportAsserts) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgAnyToGCReportAsserts) GetAsserts() []*CMsgAnyToGCReportAsserts_TrackedAssert {
	if m != nil {
		return m.Asserts
	}
	return nil
}

type CMsgAnyToGCReportAsserts_TrackedAssert struct {
	Filename             *string  `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	LineNumber           *uint32  `protobuf:"varint,2,opt,name=line_number,json=lineNumber" json:"line_number,omitempty"`
	SampleMsg            *string  `protobuf:"bytes,3,opt,name=sample_msg,json=sampleMsg" json:"sample_msg,omitempty"`
	SampleStack          *string  `protobuf:"bytes,4,opt,name=sample_stack,json=sampleStack" json:"sample_stack,omitempty"`
	TimesFired           *uint32  `protobuf:"varint,5,opt,name=times_fired,json=timesFired" json:"times_fired,omitempty"`
	FunctionName         *string  `protobuf:"bytes,6,opt,name=function_name,json=functionName" json:"function_name,omitempty"`
	Condition            *string  `protobuf:"bytes,7,opt,name=condition" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) Reset() {
	*m = CMsgAnyToGCReportAsserts_TrackedAssert{}
}
func (m *CMsgAnyToGCReportAsserts_TrackedAssert) String() string { return proto.CompactTextString(m) }
func (*CMsgAnyToGCReportAsserts_TrackedAssert) ProtoMessage()    {}
func (*CMsgAnyToGCReportAsserts_TrackedAssert) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{7, 0}
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgAnyToGCReportAsserts_TrackedAssert.Unmarshal(m, b)
}
func (m *CMsgAnyToGCReportAsserts_TrackedAssert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgAnyToGCReportAsserts_TrackedAssert.Marshal(b, m, deterministic)
}
func (m *CMsgAnyToGCReportAsserts_TrackedAssert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgAnyToGCReportAsserts_TrackedAssert.Merge(m, src)
}
func (m *CMsgAnyToGCReportAsserts_TrackedAssert) XXX_Size() int {
	return xxx_messageInfo_CMsgAnyToGCReportAsserts_TrackedAssert.Size(m)
}
func (m *CMsgAnyToGCReportAsserts_TrackedAssert) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgAnyToGCReportAsserts_TrackedAssert.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgAnyToGCReportAsserts_TrackedAssert proto.InternalMessageInfo

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetLineNumber() uint32 {
	if m != nil && m.LineNumber != nil {
		return *m.LineNumber
	}
	return 0
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetSampleMsg() string {
	if m != nil && m.SampleMsg != nil {
		return *m.SampleMsg
	}
	return ""
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetSampleStack() string {
	if m != nil && m.SampleStack != nil {
		return *m.SampleStack
	}
	return ""
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetTimesFired() uint32 {
	if m != nil && m.TimesFired != nil {
		return *m.TimesFired
	}
	return 0
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetFunctionName() string {
	if m != nil && m.FunctionName != nil {
		return *m.FunctionName
	}
	return ""
}

func (m *CMsgAnyToGCReportAsserts_TrackedAssert) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

type CMsgAnyToGCReportAssertsResponse struct {
	Success              *bool    `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgAnyToGCReportAssertsResponse) Reset()         { *m = CMsgAnyToGCReportAssertsResponse{} }
func (m *CMsgAnyToGCReportAssertsResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgAnyToGCReportAssertsResponse) ProtoMessage()    {}
func (*CMsgAnyToGCReportAssertsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ce59cd0086f1143, []int{8}
}

func (m *CMsgAnyToGCReportAssertsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgAnyToGCReportAssertsResponse.Unmarshal(m, b)
}
func (m *CMsgAnyToGCReportAssertsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgAnyToGCReportAssertsResponse.Marshal(b, m, deterministic)
}
func (m *CMsgAnyToGCReportAssertsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgAnyToGCReportAssertsResponse.Merge(m, src)
}
func (m *CMsgAnyToGCReportAssertsResponse) XXX_Size() int {
	return xxx_messageInfo_CMsgAnyToGCReportAssertsResponse.Size(m)
}
func (m *CMsgAnyToGCReportAssertsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgAnyToGCReportAssertsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgAnyToGCReportAssertsResponse proto.InternalMessageInfo

func (m *CMsgAnyToGCReportAssertsResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("protocol.EGCDACCommonMessages", EGCDACCommonMessages_name, EGCDACCommonMessages_value)
	proto.RegisterEnum("protocol.EDACMatchMode", EDACMatchMode_name, EDACMatchMode_value)
	proto.RegisterEnum("protocol.EDACGameMode", EDACGameMode_name, EDACGameMode_value)
	proto.RegisterEnum("protocol.EDACLobbyTeam", EDACLobbyTeam_name, EDACLobbyTeam_value)
	proto.RegisterEnum("protocol.EDACAIType", EDACAIType_name, EDACAIType_value)
	proto.RegisterEnum("protocol.EDACMatchState", EDACMatchState_name, EDACMatchState_value)
	proto.RegisterEnum("protocol.EDACPlayerState", EDACPlayerState_name, EDACPlayerState_value)
	proto.RegisterEnum("protocol.ELobbyServerState", ELobbyServerState_name, ELobbyServerState_value)
	proto.RegisterEnum("protocol.CSODACParty_EMemberRights", CSODACParty_EMemberRights_name, CSODACParty_EMemberRights_value)
	proto.RegisterEnum("protocol.CSODACParty_EPlayerType", CSODACParty_EPlayerType_name, CSODACParty_EPlayerType_value)
	proto.RegisterEnum("protocol.CSODACParty_EBotDifficulty", CSODACParty_EBotDifficulty_name, CSODACParty_EBotDifficulty_value)
	proto.RegisterType((*CExtraMsgBlock)(nil), "protocol.CExtraMsgBlock")
	proto.RegisterType((*CServerLobbyData_PlayerInfo)(nil), "protocol.CServerLobbyData_PlayerInfo")
	proto.RegisterType((*CServerLobbyData_PlayerInfo_LoadoutSlot)(nil), "protocol.CServerLobbyData_PlayerInfo.LoadoutSlot")
	proto.RegisterType((*CServerLobbyData_PlayerInfo_Currency)(nil), "protocol.CServerLobbyData_PlayerInfo.Currency")
	proto.RegisterType((*CServerLobbyData_PlayerInfo_Challenge)(nil), "protocol.CServerLobbyData_PlayerInfo.Challenge")
	proto.RegisterType((*CServerLobbyData_PlayerInfo_VirtualItem)(nil), "protocol.CServerLobbyData_PlayerInfo.VirtualItem")
	proto.RegisterType((*CServerLobbyData_PlayerInfo_Event)(nil), "protocol.CServerLobbyData_PlayerInfo.Event")
	proto.RegisterType((*CMsgRegionPingTimesClient)(nil), "protocol.CMsgRegionPingTimesClient")
	proto.RegisterType((*CSODACLobby)(nil), "protocol.CSODACLobby")
	proto.RegisterType((*CSODACParty)(nil), "protocol.CSODACParty")
	proto.RegisterType((*CSODACParty_Member)(nil), "protocol.CSODACParty.Member")
	proto.RegisterType((*CSODACParty_LeftMember)(nil), "protocol.CSODACParty.LeftMember")
	proto.RegisterType((*CSODACParty_Invite)(nil), "protocol.CSODACParty.Invite")
	proto.RegisterType((*CSOGameAccountClient)(nil), "protocol.CSOGameAccountClient")
	proto.RegisterType((*CMsgStartFindingMatchInfo)(nil), "protocol.CMsgStartFindingMatchInfo")
	proto.RegisterType((*CMsgAnyToGCReportAsserts)(nil), "protocol.CMsgAnyToGCReportAsserts")
	proto.RegisterType((*CMsgAnyToGCReportAsserts_TrackedAssert)(nil), "protocol.CMsgAnyToGCReportAsserts.TrackedAssert")
	proto.RegisterType((*CMsgAnyToGCReportAssertsResponse)(nil), "protocol.CMsgAnyToGCReportAssertsResponse")
}

func init() {
	proto.RegisterFile("dac_gcmessages_common.proto", fileDescriptor_9ce59cd0086f1143)
}

var fileDescriptor_9ce59cd0086f1143 = []byte{
	// 2502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcf, 0x73, 0x1b, 0xb7,
	0xf5, 0xf7, 0x92, 0x94, 0x48, 0x3e, 0x8a, 0x32, 0x82, 0xc8, 0x16, 0x4d, 0x59, 0x31, 0x4d, 0xff,
	0x88, 0xa2, 0x7c, 0xbf, 0xaa, 0x2d, 0x3b, 0x8a, 0xe2, 0xf6, 0x22, 0xad, 0x64, 0x87, 0x8d, 0x65,
	0x6b, 0x96, 0x6e, 0xa6, 0xd3, 0xcb, 0x0e, 0xb8, 0x0b, 0xae, 0x51, 0xee, 0x0f, 0x66, 0x01, 0xca,
	0xe1, 0x2d, 0x97, 0x4e, 0xce, 0x3d, 0x75, 0x7a, 0xe9, 0xa5, 0x33, 0x9d, 0x5e, 0x7a, 0xee, 0xa1,
	0x39, 0xf4, 0xcf, 0x68, 0x0f, 0x9d, 0xe9, 0x3f, 0x90, 0x4b, 0xdb, 0xb4, 0x9d, 0x9e, 0x3a, 0x00,
	0x76, 0x97, 0x4b, 0x69, 0x99, 0xb8, 0x93, 0x5c, 0x24, 0xe2, 0xf3, 0x79, 0x78, 0x78, 0x78, 0x78,
	0xef, 0xe1, 0x61, 0x61, 0xc3, 0x25, 0x8e, 0xed, 0x39, 0x01, 0xe5, 0x9c, 0x78, 0x94, 0xdb, 0x4e,
	0x14, 0x04, 0x51, 0xb8, 0x33, 0x8e, 0x23, 0x11, 0xe1, 0x9a, 0xfa, 0xe7, 0x44, 0x7e, 0xfb, 0x4d,
	0x2e, 0x28, 0x09, 0x52, 0x29, 0x4d, 0x77, 0x7f, 0x66, 0xc0, 0xaa, 0x79, 0xfc, 0xa9, 0x88, 0xc9,
	0x09, 0xf7, 0x0e, 0xfd, 0xc8, 0x19, 0xe1, 0x6b, 0x50, 0x0b, 0xb8, 0x67, 0x8b, 0xe9, 0x98, 0xb6,
	0x8c, 0x8e, 0xb1, 0xd5, 0xb4, 0xaa, 0x01, 0xf7, 0x5e, 0x4c, 0xc7, 0x14, 0xb7, 0xa1, 0xe6, 0x44,
	0xa1, 0xa0, 0xa1, 0xe0, 0xad, 0x52, 0xc7, 0xd8, 0x5a, 0xb1, 0xb2, 0x31, 0x5e, 0x07, 0x29, 0x66,
	0x8f, 0xe8, 0xb4, 0x55, 0xee, 0x18, 0x5b, 0x15, 0x6b, 0x39, 0xe0, 0xde, 0x47, 0x74, 0x8a, 0x6f,
	0x41, 0x93, 0x29, 0xa3, 0xc6, 0x31, 0xe5, 0x9c, 0xba, 0xad, 0x4a, 0xc7, 0xd8, 0xaa, 0x59, 0x2b,
	0x8c, 0x9b, 0x19, 0xd6, 0xfd, 0xb2, 0x06, 0x1b, 0x66, 0x9f, 0xc6, 0x67, 0x34, 0x7e, 0x1a, 0x0d,
	0x06, 0xd3, 0x23, 0x22, 0x88, 0x7d, 0xea, 0x93, 0x29, 0x8d, 0x7b, 0xe1, 0x30, 0xc2, 0x9b, 0x00,
	0xc4, 0x71, 0xa2, 0x49, 0x28, 0x6c, 0xe6, 0x26, 0x66, 0xd5, 0x13, 0xa4, 0xe7, 0xe2, 0x0d, 0xa8,
	0x07, 0x41, 0x6c, 0xfb, 0xf4, 0x8c, 0xfa, 0xca, 0xb2, 0xa6, 0x55, 0x0b, 0x82, 0xf8, 0xa9, 0x1c,
	0xe3, 0x8f, 0xa0, 0xea, 0x47, 0xc4, 0x8d, 0x26, 0xa2, 0x55, 0xee, 0x94, 0xb7, 0x1a, 0xbb, 0xf7,
	0x77, 0x52, 0xa7, 0xec, 0x7c, 0xcd, 0x9a, 0x3b, 0x4f, 0xf5, 0xa4, 0xbe, 0x1f, 0x09, 0x2b, 0xd5,
	0x80, 0x4d, 0x58, 0xa6, 0x67, 0xca, 0x01, 0x15, 0xa5, 0xeb, 0xdd, 0xd7, 0xd3, 0x75, 0x2c, 0xe7,
	0x58, 0xc9, 0x54, 0xbc, 0x07, 0xeb, 0x9e, 0x1f, 0x0d, 0x88, 0x6f, 0xfb, 0x94, 0xb8, 0x34, 0x1e,
	0x44, 0x24, 0x76, 0xed, 0x98, 0x84, 0xa3, 0xd6, 0x92, 0x32, 0xfe, 0x8a, 0xa6, 0x9f, 0xce, 0x58,
	0x8b, 0x84, 0x23, 0x7c, 0x1d, 0xea, 0x93, 0xd0, 0xa5, 0xb1, 0x1f, 0xc5, 0x6e, 0x6b, 0x59, 0x3b,
	0x21, 0x03, 0xda, 0xaf, 0xa0, 0x91, 0x33, 0x19, 0xdf, 0x84, 0x95, 0xc4, 0x68, 0x9b, 0xfb, 0x91,
	0x48, 0x9c, 0xd6, 0xf0, 0x73, 0x22, 0x1b, 0x50, 0x77, 0xe9, 0xd0, 0x66, 0xa1, 0x4b, 0x3f, 0x4d,
	0xdd, 0xe6, 0xd2, 0x61, 0x4f, 0x8e, 0xf1, 0x16, 0xa0, 0x6c, 0xfe, 0x64, 0xa0, 0x75, 0x94, 0x95,
	0xcc, 0x6a, 0xaa, 0x63, 0x32, 0x90, 0x6a, 0xda, 0x26, 0xd4, 0xcc, 0x49, 0x1c, 0xd3, 0xd0, 0x99,
	0xe2, 0x1b, 0xd0, 0x70, 0x92, 0xdf, 0xb3, 0x93, 0x82, 0x14, 0xea, 0xb9, 0xf8, 0x2a, 0x2c, 0x93,
	0x40, 0x1e, 0x5b, 0xb2, 0x60, 0x32, 0x6a, 0xff, 0xc1, 0x80, 0xba, 0xf9, 0x92, 0xf8, 0x3e, 0x0d,
	0x3d, 0x2a, 0x8d, 0x77, 0xd2, 0xc1, 0x4c, 0x4f, 0x23, 0xc3, 0x7a, 0xae, 0x0c, 0xc6, 0x71, 0x1c,
	0x79, 0x32, 0x80, 0x52, 0xdb, 0xd3, 0xb1, 0xb4, 0x82, 0xd3, 0x4f, 0x26, 0x34, 0x74, 0xd4, 0x6c,
	0x6d, 0x36, 0xa4, 0x50, 0xcf, 0x95, 0xd1, 0x2a, 0x37, 0x24, 0xc9, 0x8a, 0x36, 0x43, 0x0e, 0x75,
	0x24, 0x39, 0x51, 0x38, 0x64, 0x9e, 0xa4, 0xf4, 0x61, 0xd4, 0x34, 0xd0, 0x73, 0x71, 0x0b, 0xaa,
	0x8e, 0x4f, 0x58, 0x40, 0x53, 0xef, 0xa7, 0xc3, 0x76, 0x04, 0x8d, 0x8f, 0x59, 0x2c, 0x26, 0xc4,
	0xef, 0x09, 0x1a, 0xcc, 0x3b, 0xd6, 0x38, 0xe7, 0xd8, 0x4d, 0x00, 0xfa, 0xc9, 0x84, 0x8d, 0xb5,
	0x4b, 0xb5, 0xe9, 0x75, 0x85, 0xa8, 0x43, 0xb9, 0x0d, 0xab, 0x09, 0x3d, 0xef, 0xf5, 0x15, 0x2d,
	0x92, 0xf8, 0xfc, 0x8b, 0x12, 0x2c, 0xa9, 0xa0, 0x92, 0xf9, 0xaa, 0xc2, 0x6a, 0xe6, 0xa6, 0xaa,
	0x1a, 0xf7, 0x5c, 0xe9, 0x06, 0x4d, 0x45, 0xaf, 0x42, 0xea, 0xaa, 0xa5, 0x6a, 0x16, 0x28, 0xe8,
	0xb9, 0x44, 0xf0, 0x73, 0x80, 0xcc, 0xa5, 0x3c, 0xc9, 0x8e, 0xef, 0xbd, 0x5e, 0x44, 0x67, 0x67,
	0x65, 0xe5, 0x54, 0xe0, 0x67, 0x90, 0x9e, 0x35, 0xa3, 0x69, 0x8a, 0xec, 0xbc, 0xa6, 0xc2, 0x24,
	0x46, 0xac, 0x9c, 0x06, 0xfc, 0x31, 0x34, 0xcf, 0xb4, 0x5f, 0x6d, 0x26, 0x68, 0xc0, 0x5b, 0x4b,
	0xff, 0x4b, 0x06, 0xe7, 0x8e, 0xc4, 0x5a, 0x39, 0x9b, 0x0d, 0x78, 0x37, 0x84, 0x6b, 0xe6, 0x09,
	0xf7, 0x2c, 0xea, 0xb1, 0x28, 0x3c, 0x65, 0xa1, 0xf7, 0x82, 0x05, 0x94, 0x9b, 0x3e, 0x93, 0x1e,
	0xdd, 0x81, 0x37, 0x5c, 0xa9, 0xc9, 0xa1, 0xa1, 0xa0, 0xb1, 0xed, 0x44, 0x2e, 0xe5, 0x2d, 0xa3,
	0x53, 0xde, 0xaa, 0x1e, 0x96, 0x90, 0x61, 0x5d, 0x96, 0xa4, 0xa9, 0x38, 0x53, 0x52, 0xf8, 0x26,
	0xc0, 0x98, 0x85, 0x9e, 0x2d, 0xa4, 0x8e, 0x56, 0xa9, 0x53, 0xde, 0x6a, 0x2a, 0xc1, 0xfa, 0x38,
	0x55, 0xdc, 0xfd, 0x79, 0x05, 0x1a, 0x66, 0xff, 0xf9, 0xd1, 0x81, 0xa9, 0x0c, 0xc5, 0x77, 0x60,
	0x95, 0x2b, 0xbb, 0xed, 0x33, 0x1a, 0x73, 0x16, 0x85, 0xc9, 0xd1, 0x35, 0x35, 0xfa, 0xb1, 0x06,
	0xf1, 0x03, 0xb8, 0x22, 0x0b, 0x27, 0x11, 0x6c, 0xc0, 0x7c, 0x26, 0xa6, 0x99, 0xb4, 0x8e, 0x9a,
	0xb5, 0x39, 0x32, 0x9d, 0x74, 0x17, 0x2e, 0x27, 0xba, 0x55, 0xc5, 0x4f, 0x13, 0x60, 0x39, 0x55,
	0xde, 0x97, 0x68, 0xcf, 0x95, 0x81, 0xe3, 0x4b, 0x63, 0xd2, 0x48, 0xaf, 0xc8, 0x2a, 0x37, 0x18,
	0x4c, 0x35, 0x15, 0x10, 0xe1, 0xbc, 0x94, 0xd4, 0xb2, 0xa6, 0xd4, 0xb8, 0xe7, 0xe2, 0x9f, 0xc0,
	0x4a, 0xa6, 0x9d, 0x08, 0xda, 0xaa, 0x75, 0x8c, 0xad, 0xd5, 0xdd, 0x8d, 0xd9, 0x81, 0x1c, 0xab,
	0x1d, 0xf6, 0x93, 0xa5, 0x88, 0xa0, 0x8f, 0xda, 0x23, 0x9b, 0x9e, 0x07, 0xed, 0x03, 0xce, 0x99,
	0x17, 0x5a, 0x0d, 0x3e, 0xc3, 0x64, 0x38, 0xea, 0x65, 0x83, 0xc8, 0xa5, 0x2d, 0x50, 0x9a, 0xd7,
	0x73, 0x9a, 0x8f, 0x0e, 0xcc, 0x13, 0xc9, 0x9f, 0x44, 0x2e, 0x7d, 0xb4, 0x3e, 0xb2, 0xe7, 0x00,
	0xbb, 0x17, 0x9e, 0x11, 0x9f, 0xb9, 0x56, 0x3d, 0x48, 0x21, 0x99, 0x4b, 0x13, 0x77, 0x6c, 0x3b,
	0x51, 0x18, 0x52, 0x47, 0xd8, 0x6c, 0xdc, 0x6a, 0xe8, 0x5c, 0x9a, 0xb8, 0x63, 0x53, 0x83, 0xbd,
	0xb1, 0xac, 0x74, 0x79, 0xa9, 0x71, 0x14, 0x8b, 0xd6, 0x8a, 0xae, 0x74, 0x33, 0xb9, 0xd3, 0x28,
	0x16, 0xf8, 0x23, 0xa8, 0x7b, 0x24, 0xa0, 0xda, 0xbe, 0xa6, 0xb2, 0xef, 0xea, 0xbc, 0x7d, 0x4f,
	0x48, 0x40, 0x95, 0x79, 0x57, 0xb5, 0x79, 0xe9, 0x38, 0xb3, 0xae, 0xe6, 0x25, 0x48, 0xf7, 0x17,
	0x8d, 0x34, 0x26, 0x4e, 0x49, 0x2c, 0xa6, 0xd2, 0xe9, 0x63, 0xf9, 0x23, 0x4d, 0xe4, 0x8a, 0x55,
	0x55, 0xe3, 0x9e, 0x8b, 0xf7, 0xa0, 0x1a, 0xd0, 0x60, 0x40, 0x63, 0x1d, 0x5e, 0x8d, 0xdd, 0xeb,
	0xf9, 0x04, 0xc8, 0x54, 0xec, 0x9c, 0x28, 0x21, 0x2b, 0x15, 0x96, 0xf3, 0x58, 0x78, 0xc6, 0x44,
	0x96, 0xdc, 0x0b, 0xe6, 0xf5, 0x94, 0x90, 0x95, 0x0a, 0xcb, 0x10, 0x62, 0xa1, 0x9d, 0x9c, 0x05,
	0x19, 0xb1, 0xd0, 0x53, 0x11, 0x52, 0xb3, 0x9a, 0x2c, 0xd4, 0x0e, 0x57, 0xa0, 0x0c, 0x63, 0x6d,
	0xf2, 0x98, 0x70, 0xfe, 0x2a, 0xbd, 0x95, 0xea, 0x56, 0x53, 0xa1, 0xa7, 0x09, 0x88, 0x4d, 0x58,
	0xf1, 0xe9, 0x50, 0xd8, 0xe9, 0x1e, 0x40, 0xd9, 0xd2, 0x29, 0xb6, 0xe5, 0x29, 0x1d, 0x8a, 0x64,
	0x1f, 0x0d, 0x3f, 0xfb, 0xcd, 0x65, 0x4d, 0xfd, 0x69, 0xc4, 0x42, 0x95, 0x8e, 0xea, 0x18, 0x2b,
	0x56, 0x4d, 0x02, 0x32, 0x07, 0xf1, 0x00, 0x56, 0x07, 0x91, 0xb0, 0x5d, 0x36, 0x1c, 0x32, 0x67,
	0xe2, 0x8b, 0xa9, 0x3a, 0xc0, 0xd5, 0xdd, 0xdb, 0xc5, 0x6b, 0x1c, 0x1f, 0x46, 0xe2, 0x28, 0x93,
	0x7d, 0x74, 0x65, 0x64, 0xd3, 0x39, 0xc4, 0x7e, 0x16, 0x85, 0xd4, 0x6a, 0x0e, 0xf2, 0x58, 0xfb,
	0xaf, 0x25, 0x58, 0xd6, 0xc6, 0x7c, 0x53, 0x3b, 0x72, 0x13, 0x56, 0xc6, 0x34, 0xe6, 0x51, 0x48,
	0xec, 0x90, 0x04, 0x54, 0x65, 0x6b, 0xdd, 0x6a, 0x24, 0xd8, 0x33, 0x12, 0xa8, 0x0b, 0x2e, 0x66,
	0xde, 0x4b, 0xc1, 0xed, 0xa1, 0x4f, 0x3c, 0x9e, 0xd4, 0xf8, 0x86, 0xc6, 0x1e, 0x4b, 0x48, 0xc6,
	0x03, 0xe3, 0x76, 0x4c, 0x89, 0x3b, 0x4d, 0x7a, 0xa6, 0x2a, 0xe3, 0x96, 0x1c, 0xe2, 0x1f, 0x43,
	0x63, 0xac, 0xca, 0x9c, 0x6e, 0xd3, 0x96, 0xd4, 0x5e, 0x6f, 0x2e, 0xd8, 0xab, 0x2e, 0x88, 0xb2,
	0x81, 0x7b, 0xb4, 0x36, 0xb2, 0xe9, 0x6c, 0x98, 0x94, 0x4a, 0x0b, 0xc6, 0x19, 0xb4, 0xb8, 0xe2,
	0x2c, 0x7f, 0x4d, 0xc5, 0x79, 0x02, 0xb5, 0xb1, 0x4f, 0xc4, 0x30, 0x8a, 0x83, 0x56, 0xb5, 0x28,
	0x2b, 0x4e, 0x13, 0xf6, 0xd1, 0x9b, 0x23, 0x9b, 0xe6, 0xc6, 0xda, 0xcf, 0xd9, 0xe4, 0xf6, 0x6f,
	0x0d, 0x80, 0xd9, 0xf9, 0xbf, 0x86, 0x9b, 0xe7, 0x7c, 0x58, 0xba, 0xe8, 0xc3, 0x73, 0x8e, 0x2a,
	0x7f, 0x67, 0x8e, 0x6a, 0x33, 0x58, 0xd6, 0x59, 0xf3, 0x1d, 0x04, 0xc3, 0x26, 0x80, 0xce, 0x3c,
	0xd7, 0x1e, 0x4c, 0x93, 0x50, 0xa8, 0x27, 0xc8, 0xe1, 0xb4, 0xfb, 0xb9, 0x01, 0xcd, 0xe3, 0x24,
	0x25, 0xd4, 0xde, 0xf0, 0x35, 0x90, 0x21, 0x9b, 0x87, 0xec, 0x03, 0x37, 0x60, 0x21, 0x32, 0xf0,
	0x06, 0xac, 0x9f, 0xa7, 0xcc, 0x98, 0x12, 0x11, 0xc5, 0xa8, 0x84, 0xaf, 0x43, 0xeb, 0x3c, 0x29,
	0x1b, 0x4b, 0xea, 0x9e, 0x9c, 0xa0, 0x0a, 0xee, 0xc0, 0xf5, 0xf3, 0xec, 0x87, 0xcc, 0x7b, 0x99,
	0x49, 0xd4, 0xba, 0x47, 0xd0, 0xc8, 0x79, 0x09, 0xb7, 0xa0, 0xd0, 0x4f, 0xe8, 0x52, 0x62, 0x45,
	0x8e, 0xe9, 0x8f, 0xa9, 0x23, 0x94, 0x15, 0x46, 0xf7, 0x57, 0x06, 0xac, 0xce, 0x67, 0x60, 0xb2,
	0xa1, 0x8b, 0x39, 0x88, 0x2e, 0x15, 0x52, 0xc7, 0x84, 0x4f, 0xb3, 0xbd, 0xce, 0x53, 0x27, 0xd4,
	0x65, 0x93, 0x00, 0x95, 0x0a, 0xe7, 0x7d, 0x48, 0x62, 0x17, 0x95, 0xf1, 0x5b, 0xd0, 0xbe, 0xb8,
	0x9a, 0xdc, 0x70, 0x40, 0x62, 0x8a, 0x2a, 0xdd, 0xbf, 0x94, 0x60, 0xcd, 0xec, 0x3f, 0x97, 0xb5,
	0xfb, 0x40, 0x9f, 0x63, 0xd2, 0x19, 0xdc, 0xba, 0x78, 0xd4, 0x87, 0x95, 0xcf, 0x7e, 0xb3, 0x69,
	0xbc, 0xf6, 0x63, 0xe4, 0x6d, 0xb8, 0xac, 0xc9, 0xac, 0xb3, 0x4f, 0x9b, 0x6a, 0x25, 0x92, 0xa1,
	0x78, 0x0d, 0x96, 0x74, 0x54, 0x57, 0x54, 0xa9, 0xd3, 0x03, 0xfc, 0x10, 0xae, 0x4e, 0x42, 0xf9,
	0x4c, 0x53, 0xaf, 0x05, 0xea, 0xda, 0x59, 0x0b, 0xac, 0x7b, 0xd5, 0x35, 0xcd, 0xea, 0x23, 0x3b,
	0x4d, 0xdb, 0xe1, 0x77, 0x00, 0x11, 0x47, 0xb0, 0x33, 0x6a, 0xcf, 0x9e, 0x0f, 0x55, 0x25, 0x7f,
	0x59, 0xe3, 0x3f, 0x4a, 0x61, 0xfc, 0x7d, 0x68, 0x67, 0xc6, 0xdb, 0xb2, 0x8a, 0x33, 0xe2, 0xcf,
	0x16, 0x91, 0x45, 0xa0, 0x64, 0xad, 0xa7, 0xbb, 0x39, 0xd5, 0x7c, 0xb6, 0xce, 0xdd, 0x74, 0x73,
	0x72, 0x32, 0x77, 0xa2, 0x58, 0xb7, 0x07, 0x4d, 0xab, 0x99, 0xce, 0xe8, 0x4b, 0xb0, 0xfb, 0xc7,
	0x92, 0x6e, 0xbf, 0xfa, 0x82, 0xc4, 0xe2, 0x31, 0x0b, 0x5d, 0x16, 0x7a, 0xea, 0x5a, 0x51, 0x6f,
	0xbd, 0x3b, 0xb0, 0xea, 0x28, 0x77, 0x9f, 0xeb, 0x76, 0x9a, 0x1a, 0x4d, 0x8b, 0xce, 0x7c, 0xb3,
	0x50, 0xfe, 0xf6, 0xcd, 0x42, 0xbe, 0x8a, 0x55, 0xbe, 0x45, 0x15, 0x2b, 0xb8, 0x8c, 0x96, 0xbe,
	0xeb, 0xcb, 0xa8, 0xfb, 0x55, 0x09, 0x5a, 0xd2, 0x85, 0x07, 0xe1, 0xf4, 0x45, 0xf4, 0xc4, 0xb4,
	0xa8, 0xec, 0x5a, 0x0e, 0x38, 0xa7, 0xb1, 0xe0, 0xf2, 0x9d, 0x32, 0xdf, 0x56, 0xa6, 0x43, 0xfc,
	0x43, 0xa8, 0x12, 0x2d, 0x94, 0x34, 0x12, 0xf7, 0x72, 0x36, 0x2d, 0x50, 0xb7, 0xf3, 0x22, 0x26,
	0xce, 0x88, 0xba, 0x7a, 0x68, 0xa5, 0x0a, 0xda, 0x7f, 0x33, 0xa0, 0x39, 0x47, 0xc9, 0x27, 0xd9,
	0x90, 0xf9, 0x54, 0x95, 0x39, 0x43, 0x95, 0xb9, 0x6c, 0x2c, 0xdf, 0x22, 0x3e, 0x0b, 0xa9, 0x1d,
	0x4e, 0x64, 0x79, 0x49, 0x8e, 0x14, 0x24, 0xf4, 0x6c, 0x92, 0x16, 0x7b, 0x4e, 0x82, 0xb1, 0x4f,
	0xed, 0x80, 0x7b, 0xea, 0x3c, 0xeb, 0x56, 0x5d, 0x23, 0x27, 0xdc, 0x93, 0x65, 0x34, 0xa1, 0xb9,
	0x20, 0xce, 0x48, 0x9d, 0x50, 0xdd, 0x6a, 0x68, 0xac, 0x2f, 0x21, 0xb9, 0x84, 0x6a, 0xc1, 0xed,
	0x21, 0x8b, 0x69, 0xfa, 0x7a, 0x03, 0x05, 0x3d, 0x96, 0x08, 0xbe, 0x05, 0xcd, 0xe1, 0x24, 0x74,
	0x04, 0x8b, 0x42, 0x5d, 0x8b, 0x75, 0xb7, 0xb2, 0x92, 0x82, 0xaa, 0x18, 0x5f, 0x57, 0x2f, 0x40,
	0x97, 0x49, 0x40, 0x65, 0x49, 0xdd, 0x9a, 0x01, 0xdd, 0x1f, 0x40, 0x67, 0x91, 0x9f, 0x2c, 0xca,
	0xc7, 0x51, 0xc8, 0x65, 0x59, 0xac, 0xf2, 0x89, 0xe3, 0xc8, 0x84, 0x31, 0xf4, 0xbd, 0x9d, 0x0c,
	0xb7, 0xbf, 0x2c, 0xc1, 0xda, 0xf1, 0x13, 0xf3, 0xe8, 0xc0, 0x34, 0xd5, 0x47, 0x9a, 0x93, 0xe4,
	0x6b, 0x0c, 0xbe, 0x21, 0x2b, 0xd2, 0xf1, 0x02, 0xc5, 0xe8, 0x4f, 0x7b, 0xf8, 0x6d, 0xe8, 0x2e,
	0x16, 0x48, 0x57, 0x46, 0x7f, 0xde, 0xc3, 0xdb, 0x70, 0x47, 0x0b, 0x3e, 0x31, 0xe5, 0x53, 0xe7,
	0xd8, 0x65, 0x22, 0x8a, 0x2d, 0x2a, 0xdb, 0x6c, 0x22, 0x77, 0xc0, 0x2d, 0xf9, 0x0a, 0xe6, 0x02,
	0xfd, 0x7d, 0x1f, 0xbf, 0x0b, 0x77, 0xbf, 0x49, 0x36, 0x51, 0xfc, 0x8f, 0x7d, 0x7c, 0x07, 0x3a,
	0x8b, 0x84, 0xa9, 0x04, 0x8e, 0xe8, 0x10, 0x7d, 0xb5, 0x8f, 0xff, 0x1f, 0xb6, 0xbe, 0x49, 0x2c,
	0xd3, 0xfa, 0xcf, 0x7d, 0xfc, 0x0e, 0xdc, 0x2e, 0x12, 0xf7, 0x29, 0xe1, 0x34, 0x67, 0x09, 0xfa,
	0xd7, 0x3e, 0xbe, 0x0f, 0xff, 0xf7, 0x3a, 0xa2, 0x99, 0xf6, 0x7f, 0xef, 0x6f, 0xff, 0x5a, 0xde,
	0x9c, 0xf9, 0xbc, 0xd7, 0x57, 0x46, 0x61, 0x29, 0x40, 0x97, 0x70, 0x1b, 0xae, 0x9e, 0x27, 0x4d,
	0xc2, 0x27, 0xc4, 0x47, 0x86, 0xbe, 0x1c, 0xe7, 0xb9, 0xd3, 0x98, 0x9d, 0x11, 0xa1, 0x9f, 0x36,
	0xa8, 0x54, 0xa4, 0xba, 0x1f, 0xf9, 0xd1, 0x61, 0x24, 0x50, 0xb9, 0x48, 0xb5, 0x2e, 0xd2, 0xa8,
	0xb2, 0xfd, 0x99, 0x01, 0x2b, 0xf9, 0xb7, 0xc2, 0x4c, 0xf8, 0xfc, 0xeb, 0x21, 0xbd, 0x0e, 0xe7,
	0xb8, 0x67, 0x51, 0x1c, 0x28, 0x13, 0xd5, 0x75, 0x3c, 0x47, 0xbd, 0x98, 0xc4, 0x83, 0x08, 0x95,
	0xf0, 0x0d, 0xd8, 0x38, 0xc7, 0x1c, 0x4e, 0x5c, 0x77, 0x7a, 0x48, 0x84, 0xf0, 0x29, 0x47, 0xe5,
	0xed, 0xcf, 0x4b, 0xda, 0x51, 0x6a, 0x2f, 0x2f, 0x28, 0x09, 0x66, 0xeb, 0x64, 0x90, 0x2d, 0xff,
	0xdc, 0xcb, 0x9b, 0x30, 0x4f, 0xdd, 0x47, 0xc6, 0x22, 0x6a, 0x37, 0xbd, 0x8f, 0x2f, 0x52, 0x0f,
	0x50, 0x79, 0x11, 0xf5, 0x10, 0x55, 0x16, 0x51, 0xef, 0xa1, 0xa5, 0x45, 0xd4, 0x1e, 0x5a, 0x5e,
	0x44, 0xbd, 0x8f, 0xaa, 0xf8, 0x2d, 0xb8, 0x76, 0x9e, 0x9a, 0xf5, 0x26, 0xff, 0x31, 0xb6, 0x7f,
	0xbf, 0x04, 0x20, 0xe9, 0x83, 0xde, 0xac, 0xc5, 0x99, 0x8d, 0x73, 0x07, 0x71, 0x05, 0xde, 0x98,
	0x63, 0x9e, 0x9e, 0xf9, 0xd2, 0x03, 0x05, 0xb0, 0xdc, 0x7d, 0x01, 0x2c, 0x77, 0x5e, 0x00, 0xcb,
	0x5d, 0x17, 0xc0, 0x72, 0xc7, 0x05, 0xb0, 0xdc, 0x6d, 0x01, 0x2c, 0x77, 0x5a, 0x00, 0xef, 0xa3,
	0x1a, 0x5e, 0x03, 0x34, 0x07, 0x9f, 0x1e, 0xde, 0x43, 0x6b, 0x05, 0xe8, 0x7d, 0x74, 0xa5, 0x00,
	0xdd, 0x45, 0x57, 0x0b, 0xd0, 0x07, 0x68, 0xbd, 0x00, 0x7d, 0x88, 0x5a, 0x05, 0xe8, 0x7b, 0xe8,
	0x5a, 0x01, 0xba, 0x87, 0xda, 0x05, 0xe8, 0xfb, 0x68, 0xa3, 0x00, 0xdd, 0x47, 0xd7, 0x0b, 0xd0,
	0x0f, 0xd0, 0xe6, 0x85, 0x2d, 0x9f, 0x1e, 0xde, 0xbf, 0x87, 0xde, 0x2a, 0x82, 0xef, 0xa3, 0x1b,
	0x45, 0xf0, 0x2e, 0xea, 0x14, 0xc1, 0x0f, 0xd0, 0xcd, 0x22, 0xf8, 0x21, 0xea, 0x16, 0xc1, 0xef,
	0xa1, 0x5b, 0x45, 0xf0, 0x1e, 0xba, 0x5d, 0x04, 0xbf, 0x8f, 0xee, 0x14, 0xc1, 0xfb, 0xe8, 0x6e,
	0x11, 0xfc, 0x01, 0x7a, 0xbb, 0x00, 0xde, 0xbd, 0x87, 0xb6, 0xb6, 0x7f, 0x29, 0xdb, 0xea, 0xb4,
	0xc2, 0xe8, 0x0f, 0x2a, 0xaa, 0xdf, 0x3f, 0x9e, 0x01, 0x76, 0x2f, 0x4c, 0x9b, 0xb5, 0xb4, 0x49,
	0xcf, 0xb3, 0x66, 0x24, 0x2f, 0x53, 0x41, 0x5d, 0x64, 0xe0, 0xbb, 0xfa, 0xc2, 0x99, 0x91, 0x8f,
	0x09, 0xf3, 0xa9, 0x6b, 0x3f, 0xa3, 0xe2, 0x55, 0x14, 0x8f, 0x7a, 0x9c, 0x4f, 0x28, 0x47, 0x25,
	0x7c, 0x5b, 0x5f, 0x0b, 0x17, 0xe4, 0xf4, 0xb7, 0x1e, 0x33, 0x26, 0xfc, 0x25, 0x2a, 0x6f, 0xff,
	0xce, 0x80, 0xcb, 0x49, 0x0b, 0x35, 0x4d, 0xbf, 0xf6, 0xe8, 0x2a, 0x97, 0x43, 0xd4, 0xf3, 0x81,
	0x85, 0x1e, 0xba, 0x84, 0x37, 0x55, 0x96, 0xe6, 0xb9, 0x63, 0x9f, 0x05, 0x2c, 0x24, 0xda, 0x38,
	0xbd, 0xaf, 0x3c, 0x7d, 0x30, 0x20, 0xa1, 0x1b, 0x85, 0xd4, 0xcd, 0xaa, 0x5d, 0x9e, 0x3d, 0x62,
	0x3c, 0xf9, 0xba, 0x43, 0x65, 0xff, 0xaf, 0x6b, 0x79, 0x5e, 0x20, 0x67, 0xad, 0x2a, 0xc9, 0x5f,
	0x18, 0xf0, 0xc6, 0x85, 0x0f, 0x59, 0xc9, 0xbb, 0x61, 0xc1, 0xa7, 0x2c, 0x74, 0x69, 0x11, 0xdf,
	0x0b, 0x65, 0xd9, 0x45, 0x06, 0xbe, 0x09, 0x9b, 0x45, 0xfc, 0x69, 0xc4, 0x85, 0x72, 0x20, 0x2a,
	0x2d, 0x12, 0xe9, 0x33, 0x2f, 0xa4, 0xee, 0xf3, 0x89, 0xbc, 0x4a, 0x16, 0x88, 0xcc, 0x3c, 0x50,
	0x39, 0x5c, 0xfa, 0xd0, 0xf8, 0xcc, 0xb8, 0xf4, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x02,
	0x8d, 0x75, 0x1a, 0x1a, 0x00, 0x00,
}
