// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkbasetypes.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NET_Messages int32

const (
	NET_Messages_net_NOP                        NET_Messages = 0
	NET_Messages_net_Disconnect                 NET_Messages = 1
	NET_Messages_net_SplitScreenUser            NET_Messages = 3
	NET_Messages_net_Tick                       NET_Messages = 4
	NET_Messages_net_StringCmd                  NET_Messages = 5
	NET_Messages_net_SetConVar                  NET_Messages = 6
	NET_Messages_net_SignonState                NET_Messages = 7
	NET_Messages_net_SpawnGroup_Load            NET_Messages = 8
	NET_Messages_net_SpawnGroup_ManifestUpdate  NET_Messages = 9
	NET_Messages_net_SpawnGroup_SetCreationTick NET_Messages = 11
	NET_Messages_net_SpawnGroup_Unload          NET_Messages = 12
	NET_Messages_net_SpawnGroup_LoadCompleted   NET_Messages = 13
)

var NET_Messages_name = map[int32]string{
	0:  "net_NOP",
	1:  "net_Disconnect",
	3:  "net_SplitScreenUser",
	4:  "net_Tick",
	5:  "net_StringCmd",
	6:  "net_SetConVar",
	7:  "net_SignonState",
	8:  "net_SpawnGroup_Load",
	9:  "net_SpawnGroup_ManifestUpdate",
	11: "net_SpawnGroup_SetCreationTick",
	12: "net_SpawnGroup_Unload",
	13: "net_SpawnGroup_LoadCompleted",
}

var NET_Messages_value = map[string]int32{
	"net_NOP":                        0,
	"net_Disconnect":                 1,
	"net_SplitScreenUser":            3,
	"net_Tick":                       4,
	"net_StringCmd":                  5,
	"net_SetConVar":                  6,
	"net_SignonState":                7,
	"net_SpawnGroup_Load":            8,
	"net_SpawnGroup_ManifestUpdate":  9,
	"net_SpawnGroup_SetCreationTick": 11,
	"net_SpawnGroup_Unload":          12,
	"net_SpawnGroup_LoadCompleted":   13,
}

func (x NET_Messages) Enum() *NET_Messages {
	p := new(NET_Messages)
	*p = x
	return p
}

func (x NET_Messages) String() string {
	return proto.EnumName(NET_Messages_name, int32(x))
}

func (x *NET_Messages) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NET_Messages_value, data, "NET_Messages")
	if err != nil {
		return err
	}
	*x = NET_Messages(value)
	return nil
}

func (NET_Messages) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{0}
}

type SpawnGroupFlagsT int32

const (
	SpawnGroupFlagsT_SPAWN_GROUP_LOAD_ENTITIES_FROM_SAVE     SpawnGroupFlagsT = 1
	SpawnGroupFlagsT_SPAWN_GROUP_DONT_SPAWN_ENTITIES         SpawnGroupFlagsT = 2
	SpawnGroupFlagsT_SPAWN_GROUP_SYNCHRONOUS_SPAWN           SpawnGroupFlagsT = 4
	SpawnGroupFlagsT_SPAWN_GROUP_IS_INITIAL_SPAWN_GROUP      SpawnGroupFlagsT = 8
	SpawnGroupFlagsT_SPAWN_GROUP_CREATE_CLIENT_ONLY_ENTITIES SpawnGroupFlagsT = 16
	SpawnGroupFlagsT_SPAWN_GROUP_BLOCK_UNTIL_LOADED          SpawnGroupFlagsT = 64
	SpawnGroupFlagsT_SPAWN_GROUP_LOAD_STREAMING_DATA         SpawnGroupFlagsT = 128
	SpawnGroupFlagsT_SPAWN_GROUP_CREATE_NEW_SCENE_WORLD      SpawnGroupFlagsT = 256
)

var SpawnGroupFlagsT_name = map[int32]string{
	1:   "SPAWN_GROUP_LOAD_ENTITIES_FROM_SAVE",
	2:   "SPAWN_GROUP_DONT_SPAWN_ENTITIES",
	4:   "SPAWN_GROUP_SYNCHRONOUS_SPAWN",
	8:   "SPAWN_GROUP_IS_INITIAL_SPAWN_GROUP",
	16:  "SPAWN_GROUP_CREATE_CLIENT_ONLY_ENTITIES",
	64:  "SPAWN_GROUP_BLOCK_UNTIL_LOADED",
	128: "SPAWN_GROUP_LOAD_STREAMING_DATA",
	256: "SPAWN_GROUP_CREATE_NEW_SCENE_WORLD",
}

var SpawnGroupFlagsT_value = map[string]int32{
	"SPAWN_GROUP_LOAD_ENTITIES_FROM_SAVE":     1,
	"SPAWN_GROUP_DONT_SPAWN_ENTITIES":         2,
	"SPAWN_GROUP_SYNCHRONOUS_SPAWN":           4,
	"SPAWN_GROUP_IS_INITIAL_SPAWN_GROUP":      8,
	"SPAWN_GROUP_CREATE_CLIENT_ONLY_ENTITIES": 16,
	"SPAWN_GROUP_BLOCK_UNTIL_LOADED":          64,
	"SPAWN_GROUP_LOAD_STREAMING_DATA":         128,
	"SPAWN_GROUP_CREATE_NEW_SCENE_WORLD":      256,
}

func (x SpawnGroupFlagsT) Enum() *SpawnGroupFlagsT {
	p := new(SpawnGroupFlagsT)
	*p = x
	return p
}

func (x SpawnGroupFlagsT) String() string {
	return proto.EnumName(SpawnGroupFlagsT_name, int32(x))
}

func (x *SpawnGroupFlagsT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SpawnGroupFlagsT_value, data, "SpawnGroupFlagsT")
	if err != nil {
		return err
	}
	*x = SpawnGroupFlagsT(value)
	return nil
}

func (SpawnGroupFlagsT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{1}
}

type CMsgVector struct {
	X                    *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgVector) Reset()         { *m = CMsgVector{} }
func (m *CMsgVector) String() string { return proto.CompactTextString(m) }
func (*CMsgVector) ProtoMessage()    {}
func (*CMsgVector) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{0}
}

func (m *CMsgVector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgVector.Unmarshal(m, b)
}
func (m *CMsgVector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgVector.Marshal(b, m, deterministic)
}
func (m *CMsgVector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgVector.Merge(m, src)
}
func (m *CMsgVector) XXX_Size() int {
	return xxx_messageInfo_CMsgVector.Size(m)
}
func (m *CMsgVector) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgVector.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgVector proto.InternalMessageInfo

func (m *CMsgVector) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CMsgVector) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *CMsgVector) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type CMsgVector2D struct {
	X                    *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgVector2D) Reset()         { *m = CMsgVector2D{} }
func (m *CMsgVector2D) String() string { return proto.CompactTextString(m) }
func (*CMsgVector2D) ProtoMessage()    {}
func (*CMsgVector2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{1}
}

func (m *CMsgVector2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgVector2D.Unmarshal(m, b)
}
func (m *CMsgVector2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgVector2D.Marshal(b, m, deterministic)
}
func (m *CMsgVector2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgVector2D.Merge(m, src)
}
func (m *CMsgVector2D) XXX_Size() int {
	return xxx_messageInfo_CMsgVector2D.Size(m)
}
func (m *CMsgVector2D) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgVector2D.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgVector2D proto.InternalMessageInfo

func (m *CMsgVector2D) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CMsgVector2D) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type CMsgQAngle struct {
	X                    *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgQAngle) Reset()         { *m = CMsgQAngle{} }
func (m *CMsgQAngle) String() string { return proto.CompactTextString(m) }
func (*CMsgQAngle) ProtoMessage()    {}
func (*CMsgQAngle) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{2}
}

func (m *CMsgQAngle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgQAngle.Unmarshal(m, b)
}
func (m *CMsgQAngle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgQAngle.Marshal(b, m, deterministic)
}
func (m *CMsgQAngle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgQAngle.Merge(m, src)
}
func (m *CMsgQAngle) XXX_Size() int {
	return xxx_messageInfo_CMsgQAngle.Size(m)
}
func (m *CMsgQAngle) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgQAngle.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgQAngle proto.InternalMessageInfo

func (m *CMsgQAngle) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CMsgQAngle) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *CMsgQAngle) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type CMsgRGBA struct {
	R                    *int32   `protobuf:"varint,1,opt,name=r" json:"r,omitempty"`
	G                    *int32   `protobuf:"varint,2,opt,name=g" json:"g,omitempty"`
	B                    *int32   `protobuf:"varint,3,opt,name=b" json:"b,omitempty"`
	A                    *int32   `protobuf:"varint,4,opt,name=a" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgRGBA) Reset()         { *m = CMsgRGBA{} }
func (m *CMsgRGBA) String() string { return proto.CompactTextString(m) }
func (*CMsgRGBA) ProtoMessage()    {}
func (*CMsgRGBA) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{3}
}

func (m *CMsgRGBA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgRGBA.Unmarshal(m, b)
}
func (m *CMsgRGBA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgRGBA.Marshal(b, m, deterministic)
}
func (m *CMsgRGBA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgRGBA.Merge(m, src)
}
func (m *CMsgRGBA) XXX_Size() int {
	return xxx_messageInfo_CMsgRGBA.Size(m)
}
func (m *CMsgRGBA) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgRGBA.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgRGBA proto.InternalMessageInfo

func (m *CMsgRGBA) GetR() int32 {
	if m != nil && m.R != nil {
		return *m.R
	}
	return 0
}

func (m *CMsgRGBA) GetG() int32 {
	if m != nil && m.G != nil {
		return *m.G
	}
	return 0
}

func (m *CMsgRGBA) GetB() int32 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

func (m *CMsgRGBA) GetA() int32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

type CMsgPlayerInfo struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Xuid                 *uint64  `protobuf:"fixed64,2,opt,name=xuid" json:"xuid,omitempty"`
	Userid               *int32   `protobuf:"varint,3,opt,name=userid" json:"userid,omitempty"`
	Steamid              *uint64  `protobuf:"fixed64,4,opt,name=steamid" json:"steamid,omitempty"`
	Fakeplayer           *bool    `protobuf:"varint,5,opt,name=fakeplayer" json:"fakeplayer,omitempty"`
	Ishltv               *bool    `protobuf:"varint,6,opt,name=ishltv" json:"ishltv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgPlayerInfo) Reset()         { *m = CMsgPlayerInfo{} }
func (m *CMsgPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CMsgPlayerInfo) ProtoMessage()    {}
func (*CMsgPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{4}
}

func (m *CMsgPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgPlayerInfo.Unmarshal(m, b)
}
func (m *CMsgPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgPlayerInfo.Marshal(b, m, deterministic)
}
func (m *CMsgPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgPlayerInfo.Merge(m, src)
}
func (m *CMsgPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CMsgPlayerInfo.Size(m)
}
func (m *CMsgPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgPlayerInfo proto.InternalMessageInfo

func (m *CMsgPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CMsgPlayerInfo) GetXuid() uint64 {
	if m != nil && m.Xuid != nil {
		return *m.Xuid
	}
	return 0
}

func (m *CMsgPlayerInfo) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *CMsgPlayerInfo) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgPlayerInfo) GetFakeplayer() bool {
	if m != nil && m.Fakeplayer != nil {
		return *m.Fakeplayer
	}
	return false
}

func (m *CMsgPlayerInfo) GetIshltv() bool {
	if m != nil && m.Ishltv != nil {
		return *m.Ishltv
	}
	return false
}

type CEntityMsg struct {
	TargetEntity         *uint32  `protobuf:"varint,1,opt,name=target_entity,json=targetEntity" json:"target_entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CEntityMsg) Reset()         { *m = CEntityMsg{} }
func (m *CEntityMsg) String() string { return proto.CompactTextString(m) }
func (*CEntityMsg) ProtoMessage()    {}
func (*CEntityMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{5}
}

func (m *CEntityMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CEntityMsg.Unmarshal(m, b)
}
func (m *CEntityMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CEntityMsg.Marshal(b, m, deterministic)
}
func (m *CEntityMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CEntityMsg.Merge(m, src)
}
func (m *CEntityMsg) XXX_Size() int {
	return xxx_messageInfo_CEntityMsg.Size(m)
}
func (m *CEntityMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CEntityMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CEntityMsg proto.InternalMessageInfo

func (m *CEntityMsg) GetTargetEntity() uint32 {
	if m != nil && m.TargetEntity != nil {
		return *m.TargetEntity
	}
	return 0
}

type CMsg_CVars struct {
	Cvars                []*CMsg_CVars_CVar `protobuf:"bytes,1,rep,name=cvars" json:"cvars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CMsg_CVars) Reset()         { *m = CMsg_CVars{} }
func (m *CMsg_CVars) String() string { return proto.CompactTextString(m) }
func (*CMsg_CVars) ProtoMessage()    {}
func (*CMsg_CVars) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{6}
}

func (m *CMsg_CVars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsg_CVars.Unmarshal(m, b)
}
func (m *CMsg_CVars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsg_CVars.Marshal(b, m, deterministic)
}
func (m *CMsg_CVars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsg_CVars.Merge(m, src)
}
func (m *CMsg_CVars) XXX_Size() int {
	return xxx_messageInfo_CMsg_CVars.Size(m)
}
func (m *CMsg_CVars) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsg_CVars.DiscardUnknown(m)
}

var xxx_messageInfo_CMsg_CVars proto.InternalMessageInfo

func (m *CMsg_CVars) GetCvars() []*CMsg_CVars_CVar {
	if m != nil {
		return m.Cvars
	}
	return nil
}

type CMsg_CVars_CVar struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsg_CVars_CVar) Reset()         { *m = CMsg_CVars_CVar{} }
func (m *CMsg_CVars_CVar) String() string { return proto.CompactTextString(m) }
func (*CMsg_CVars_CVar) ProtoMessage()    {}
func (*CMsg_CVars_CVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{6, 0}
}

func (m *CMsg_CVars_CVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsg_CVars_CVar.Unmarshal(m, b)
}
func (m *CMsg_CVars_CVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsg_CVars_CVar.Marshal(b, m, deterministic)
}
func (m *CMsg_CVars_CVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsg_CVars_CVar.Merge(m, src)
}
func (m *CMsg_CVars_CVar) XXX_Size() int {
	return xxx_messageInfo_CMsg_CVars_CVar.Size(m)
}
func (m *CMsg_CVars_CVar) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsg_CVars_CVar.DiscardUnknown(m)
}

var xxx_messageInfo_CMsg_CVars_CVar proto.InternalMessageInfo

func (m *CMsg_CVars_CVar) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CMsg_CVars_CVar) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type CNETMsg_NOP struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_NOP) Reset()         { *m = CNETMsg_NOP{} }
func (m *CNETMsg_NOP) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_NOP) ProtoMessage()    {}
func (*CNETMsg_NOP) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{7}
}

func (m *CNETMsg_NOP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_NOP.Unmarshal(m, b)
}
func (m *CNETMsg_NOP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_NOP.Marshal(b, m, deterministic)
}
func (m *CNETMsg_NOP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_NOP.Merge(m, src)
}
func (m *CNETMsg_NOP) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_NOP.Size(m)
}
func (m *CNETMsg_NOP) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_NOP.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_NOP proto.InternalMessageInfo

type CNETMsg_SplitScreenUser struct {
	Slot                 *int32   `protobuf:"varint,1,opt,name=slot" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_SplitScreenUser) Reset()         { *m = CNETMsg_SplitScreenUser{} }
func (m *CNETMsg_SplitScreenUser) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SplitScreenUser) ProtoMessage()    {}
func (*CNETMsg_SplitScreenUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{8}
}

func (m *CNETMsg_SplitScreenUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SplitScreenUser.Unmarshal(m, b)
}
func (m *CNETMsg_SplitScreenUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SplitScreenUser.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SplitScreenUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SplitScreenUser.Merge(m, src)
}
func (m *CNETMsg_SplitScreenUser) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SplitScreenUser.Size(m)
}
func (m *CNETMsg_SplitScreenUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SplitScreenUser.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SplitScreenUser proto.InternalMessageInfo

func (m *CNETMsg_SplitScreenUser) GetSlot() int32 {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return 0
}

type CNETMsg_Disconnect struct {
	Reason               *ENetworkDisconnectionReason `protobuf:"varint,2,opt,name=reason,enum=protocol.ENetworkDisconnectionReason,def=0" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CNETMsg_Disconnect) Reset()         { *m = CNETMsg_Disconnect{} }
func (m *CNETMsg_Disconnect) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_Disconnect) ProtoMessage()    {}
func (*CNETMsg_Disconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{9}
}

func (m *CNETMsg_Disconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_Disconnect.Unmarshal(m, b)
}
func (m *CNETMsg_Disconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_Disconnect.Marshal(b, m, deterministic)
}
func (m *CNETMsg_Disconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_Disconnect.Merge(m, src)
}
func (m *CNETMsg_Disconnect) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_Disconnect.Size(m)
}
func (m *CNETMsg_Disconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_Disconnect.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_Disconnect proto.InternalMessageInfo

const Default_CNETMsg_Disconnect_Reason ENetworkDisconnectionReason = ENetworkDisconnectionReason_NETWORK_DISCONNECT_INVALID

func (m *CNETMsg_Disconnect) GetReason() ENetworkDisconnectionReason {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return Default_CNETMsg_Disconnect_Reason
}

type CNETMsg_Tick struct {
	Tick                            *uint32  `protobuf:"varint,1,opt,name=tick" json:"tick,omitempty"`
	HostFrametime                   *uint32  `protobuf:"varint,2,opt,name=host_frametime,json=hostFrametime" json:"host_frametime,omitempty"`
	HostFrametimeStdDeviation       *uint32  `protobuf:"varint,3,opt,name=host_frametime_std_deviation,json=hostFrametimeStdDeviation" json:"host_frametime_std_deviation,omitempty"`
	HostComputationtime             *uint32  `protobuf:"varint,4,opt,name=host_computationtime,json=hostComputationtime" json:"host_computationtime,omitempty"`
	HostComputationtimeStdDeviation *uint32  `protobuf:"varint,5,opt,name=host_computationtime_std_deviation,json=hostComputationtimeStdDeviation" json:"host_computationtime_std_deviation,omitempty"`
	HostFramestarttimeStdDeviation  *uint32  `protobuf:"varint,6,opt,name=host_framestarttime_std_deviation,json=hostFramestarttimeStdDeviation" json:"host_framestarttime_std_deviation,omitempty"`
	HostLoss                        *uint32  `protobuf:"varint,7,opt,name=host_loss,json=hostLoss" json:"host_loss,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *CNETMsg_Tick) Reset()         { *m = CNETMsg_Tick{} }
func (m *CNETMsg_Tick) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_Tick) ProtoMessage()    {}
func (*CNETMsg_Tick) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{10}
}

func (m *CNETMsg_Tick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_Tick.Unmarshal(m, b)
}
func (m *CNETMsg_Tick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_Tick.Marshal(b, m, deterministic)
}
func (m *CNETMsg_Tick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_Tick.Merge(m, src)
}
func (m *CNETMsg_Tick) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_Tick.Size(m)
}
func (m *CNETMsg_Tick) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_Tick.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_Tick proto.InternalMessageInfo

func (m *CNETMsg_Tick) GetTick() uint32 {
	if m != nil && m.Tick != nil {
		return *m.Tick
	}
	return 0
}

func (m *CNETMsg_Tick) GetHostFrametime() uint32 {
	if m != nil && m.HostFrametime != nil {
		return *m.HostFrametime
	}
	return 0
}

func (m *CNETMsg_Tick) GetHostFrametimeStdDeviation() uint32 {
	if m != nil && m.HostFrametimeStdDeviation != nil {
		return *m.HostFrametimeStdDeviation
	}
	return 0
}

func (m *CNETMsg_Tick) GetHostComputationtime() uint32 {
	if m != nil && m.HostComputationtime != nil {
		return *m.HostComputationtime
	}
	return 0
}

func (m *CNETMsg_Tick) GetHostComputationtimeStdDeviation() uint32 {
	if m != nil && m.HostComputationtimeStdDeviation != nil {
		return *m.HostComputationtimeStdDeviation
	}
	return 0
}

func (m *CNETMsg_Tick) GetHostFramestarttimeStdDeviation() uint32 {
	if m != nil && m.HostFramestarttimeStdDeviation != nil {
		return *m.HostFramestarttimeStdDeviation
	}
	return 0
}

func (m *CNETMsg_Tick) GetHostLoss() uint32 {
	if m != nil && m.HostLoss != nil {
		return *m.HostLoss
	}
	return 0
}

type CNETMsg_StringCmd struct {
	Command              *string  `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_StringCmd) Reset()         { *m = CNETMsg_StringCmd{} }
func (m *CNETMsg_StringCmd) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_StringCmd) ProtoMessage()    {}
func (*CNETMsg_StringCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{11}
}

func (m *CNETMsg_StringCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_StringCmd.Unmarshal(m, b)
}
func (m *CNETMsg_StringCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_StringCmd.Marshal(b, m, deterministic)
}
func (m *CNETMsg_StringCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_StringCmd.Merge(m, src)
}
func (m *CNETMsg_StringCmd) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_StringCmd.Size(m)
}
func (m *CNETMsg_StringCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_StringCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_StringCmd proto.InternalMessageInfo

func (m *CNETMsg_StringCmd) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

type CNETMsg_SetConVar struct {
	Convars              *CMsg_CVars `protobuf:"bytes,1,opt,name=convars" json:"convars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CNETMsg_SetConVar) Reset()         { *m = CNETMsg_SetConVar{} }
func (m *CNETMsg_SetConVar) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SetConVar) ProtoMessage()    {}
func (*CNETMsg_SetConVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{12}
}

func (m *CNETMsg_SetConVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SetConVar.Unmarshal(m, b)
}
func (m *CNETMsg_SetConVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SetConVar.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SetConVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SetConVar.Merge(m, src)
}
func (m *CNETMsg_SetConVar) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SetConVar.Size(m)
}
func (m *CNETMsg_SetConVar) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SetConVar.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SetConVar proto.InternalMessageInfo

func (m *CNETMsg_SetConVar) GetConvars() *CMsg_CVars {
	if m != nil {
		return m.Convars
	}
	return nil
}

type CNETMsg_SignonState struct {
	SignonState          *uint32  `protobuf:"varint,1,opt,name=signon_state,json=signonState" json:"signon_state,omitempty"`
	SpawnCount           *uint32  `protobuf:"varint,2,opt,name=spawn_count,json=spawnCount" json:"spawn_count,omitempty"`
	NumServerPlayers     *uint32  `protobuf:"varint,3,opt,name=num_server_players,json=numServerPlayers" json:"num_server_players,omitempty"`
	PlayersNetworkids    []string `protobuf:"bytes,4,rep,name=players_networkids,json=playersNetworkids" json:"players_networkids,omitempty"`
	MapName              *string  `protobuf:"bytes,5,opt,name=map_name,json=mapName" json:"map_name,omitempty"`
	Addons               *string  `protobuf:"bytes,6,opt,name=addons" json:"addons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_SignonState) Reset()         { *m = CNETMsg_SignonState{} }
func (m *CNETMsg_SignonState) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SignonState) ProtoMessage()    {}
func (*CNETMsg_SignonState) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{13}
}

func (m *CNETMsg_SignonState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SignonState.Unmarshal(m, b)
}
func (m *CNETMsg_SignonState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SignonState.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SignonState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SignonState.Merge(m, src)
}
func (m *CNETMsg_SignonState) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SignonState.Size(m)
}
func (m *CNETMsg_SignonState) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SignonState.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SignonState proto.InternalMessageInfo

func (m *CNETMsg_SignonState) GetSignonState() uint32 {
	if m != nil && m.SignonState != nil {
		return *m.SignonState
	}
	return 0
}

func (m *CNETMsg_SignonState) GetSpawnCount() uint32 {
	if m != nil && m.SpawnCount != nil {
		return *m.SpawnCount
	}
	return 0
}

func (m *CNETMsg_SignonState) GetNumServerPlayers() uint32 {
	if m != nil && m.NumServerPlayers != nil {
		return *m.NumServerPlayers
	}
	return 0
}

func (m *CNETMsg_SignonState) GetPlayersNetworkids() []string {
	if m != nil {
		return m.PlayersNetworkids
	}
	return nil
}

func (m *CNETMsg_SignonState) GetMapName() string {
	if m != nil && m.MapName != nil {
		return *m.MapName
	}
	return ""
}

func (m *CNETMsg_SignonState) GetAddons() string {
	if m != nil && m.Addons != nil {
		return *m.Addons
	}
	return ""
}

type CSVCMsg_GameEvent struct {
	EventName            *string                  `protobuf:"bytes,1,opt,name=event_name,json=eventName" json:"event_name,omitempty"`
	Eventid              *int32                   `protobuf:"varint,2,opt,name=eventid" json:"eventid,omitempty"`
	Keys                 []*CSVCMsg_GameEventKeyT `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CSVCMsg_GameEvent) Reset()         { *m = CSVCMsg_GameEvent{} }
func (m *CSVCMsg_GameEvent) String() string { return proto.CompactTextString(m) }
func (*CSVCMsg_GameEvent) ProtoMessage()    {}
func (*CSVCMsg_GameEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{14}
}

func (m *CSVCMsg_GameEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsg_GameEvent.Unmarshal(m, b)
}
func (m *CSVCMsg_GameEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsg_GameEvent.Marshal(b, m, deterministic)
}
func (m *CSVCMsg_GameEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsg_GameEvent.Merge(m, src)
}
func (m *CSVCMsg_GameEvent) XXX_Size() int {
	return xxx_messageInfo_CSVCMsg_GameEvent.Size(m)
}
func (m *CSVCMsg_GameEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsg_GameEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsg_GameEvent proto.InternalMessageInfo

func (m *CSVCMsg_GameEvent) GetEventName() string {
	if m != nil && m.EventName != nil {
		return *m.EventName
	}
	return ""
}

func (m *CSVCMsg_GameEvent) GetEventid() int32 {
	if m != nil && m.Eventid != nil {
		return *m.Eventid
	}
	return 0
}

func (m *CSVCMsg_GameEvent) GetKeys() []*CSVCMsg_GameEventKeyT {
	if m != nil {
		return m.Keys
	}
	return nil
}

type CSVCMsg_GameEventKeyT struct {
	Type                 *int32   `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	ValString            *string  `protobuf:"bytes,2,opt,name=val_string,json=valString" json:"val_string,omitempty"`
	ValFloat             *float32 `protobuf:"fixed32,3,opt,name=val_float,json=valFloat" json:"val_float,omitempty"`
	ValLong              *int32   `protobuf:"varint,4,opt,name=val_long,json=valLong" json:"val_long,omitempty"`
	ValShort             *int32   `protobuf:"varint,5,opt,name=val_short,json=valShort" json:"val_short,omitempty"`
	ValByte              *int32   `protobuf:"varint,6,opt,name=val_byte,json=valByte" json:"val_byte,omitempty"`
	ValBool              *bool    `protobuf:"varint,7,opt,name=val_bool,json=valBool" json:"val_bool,omitempty"`
	ValUint64            *uint64  `protobuf:"varint,8,opt,name=val_uint64,json=valUint64" json:"val_uint64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSVCMsg_GameEventKeyT) Reset()         { *m = CSVCMsg_GameEventKeyT{} }
func (m *CSVCMsg_GameEventKeyT) String() string { return proto.CompactTextString(m) }
func (*CSVCMsg_GameEventKeyT) ProtoMessage()    {}
func (*CSVCMsg_GameEventKeyT) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{14, 0}
}

func (m *CSVCMsg_GameEventKeyT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsg_GameEventKeyT.Unmarshal(m, b)
}
func (m *CSVCMsg_GameEventKeyT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsg_GameEventKeyT.Marshal(b, m, deterministic)
}
func (m *CSVCMsg_GameEventKeyT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsg_GameEventKeyT.Merge(m, src)
}
func (m *CSVCMsg_GameEventKeyT) XXX_Size() int {
	return xxx_messageInfo_CSVCMsg_GameEventKeyT.Size(m)
}
func (m *CSVCMsg_GameEventKeyT) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsg_GameEventKeyT.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsg_GameEventKeyT proto.InternalMessageInfo

func (m *CSVCMsg_GameEventKeyT) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CSVCMsg_GameEventKeyT) GetValString() string {
	if m != nil && m.ValString != nil {
		return *m.ValString
	}
	return ""
}

func (m *CSVCMsg_GameEventKeyT) GetValFloat() float32 {
	if m != nil && m.ValFloat != nil {
		return *m.ValFloat
	}
	return 0
}

func (m *CSVCMsg_GameEventKeyT) GetValLong() int32 {
	if m != nil && m.ValLong != nil {
		return *m.ValLong
	}
	return 0
}

func (m *CSVCMsg_GameEventKeyT) GetValShort() int32 {
	if m != nil && m.ValShort != nil {
		return *m.ValShort
	}
	return 0
}

func (m *CSVCMsg_GameEventKeyT) GetValByte() int32 {
	if m != nil && m.ValByte != nil {
		return *m.ValByte
	}
	return 0
}

func (m *CSVCMsg_GameEventKeyT) GetValBool() bool {
	if m != nil && m.ValBool != nil {
		return *m.ValBool
	}
	return false
}

func (m *CSVCMsg_GameEventKeyT) GetValUint64() uint64 {
	if m != nil && m.ValUint64 != nil {
		return *m.ValUint64
	}
	return 0
}

type CSVCMsgList_GameEvents struct {
	Events               []*CSVCMsgList_GameEventsEventT `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *CSVCMsgList_GameEvents) Reset()         { *m = CSVCMsgList_GameEvents{} }
func (m *CSVCMsgList_GameEvents) String() string { return proto.CompactTextString(m) }
func (*CSVCMsgList_GameEvents) ProtoMessage()    {}
func (*CSVCMsgList_GameEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{15}
}

func (m *CSVCMsgList_GameEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsgList_GameEvents.Unmarshal(m, b)
}
func (m *CSVCMsgList_GameEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsgList_GameEvents.Marshal(b, m, deterministic)
}
func (m *CSVCMsgList_GameEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsgList_GameEvents.Merge(m, src)
}
func (m *CSVCMsgList_GameEvents) XXX_Size() int {
	return xxx_messageInfo_CSVCMsgList_GameEvents.Size(m)
}
func (m *CSVCMsgList_GameEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsgList_GameEvents.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsgList_GameEvents proto.InternalMessageInfo

func (m *CSVCMsgList_GameEvents) GetEvents() []*CSVCMsgList_GameEventsEventT {
	if m != nil {
		return m.Events
	}
	return nil
}

type CSVCMsgList_GameEventsEventT struct {
	Tick                 *int32             `protobuf:"varint,1,opt,name=tick" json:"tick,omitempty"`
	Event                *CSVCMsg_GameEvent `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CSVCMsgList_GameEventsEventT) Reset()         { *m = CSVCMsgList_GameEventsEventT{} }
func (m *CSVCMsgList_GameEventsEventT) String() string { return proto.CompactTextString(m) }
func (*CSVCMsgList_GameEventsEventT) ProtoMessage()    {}
func (*CSVCMsgList_GameEventsEventT) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{15, 0}
}

func (m *CSVCMsgList_GameEventsEventT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsgList_GameEventsEventT.Unmarshal(m, b)
}
func (m *CSVCMsgList_GameEventsEventT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsgList_GameEventsEventT.Marshal(b, m, deterministic)
}
func (m *CSVCMsgList_GameEventsEventT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsgList_GameEventsEventT.Merge(m, src)
}
func (m *CSVCMsgList_GameEventsEventT) XXX_Size() int {
	return xxx_messageInfo_CSVCMsgList_GameEventsEventT.Size(m)
}
func (m *CSVCMsgList_GameEventsEventT) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsgList_GameEventsEventT.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsgList_GameEventsEventT proto.InternalMessageInfo

func (m *CSVCMsgList_GameEventsEventT) GetTick() int32 {
	if m != nil && m.Tick != nil {
		return *m.Tick
	}
	return 0
}

func (m *CSVCMsgList_GameEventsEventT) GetEvent() *CSVCMsg_GameEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

type CSVCMsg_UserMessage struct {
	MsgType              *int32   `protobuf:"varint,1,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=msg_data,json=msgData" json:"msg_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSVCMsg_UserMessage) Reset()         { *m = CSVCMsg_UserMessage{} }
func (m *CSVCMsg_UserMessage) String() string { return proto.CompactTextString(m) }
func (*CSVCMsg_UserMessage) ProtoMessage()    {}
func (*CSVCMsg_UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{16}
}

func (m *CSVCMsg_UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsg_UserMessage.Unmarshal(m, b)
}
func (m *CSVCMsg_UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsg_UserMessage.Marshal(b, m, deterministic)
}
func (m *CSVCMsg_UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsg_UserMessage.Merge(m, src)
}
func (m *CSVCMsg_UserMessage) XXX_Size() int {
	return xxx_messageInfo_CSVCMsg_UserMessage.Size(m)
}
func (m *CSVCMsg_UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsg_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsg_UserMessage proto.InternalMessageInfo

func (m *CSVCMsg_UserMessage) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *CSVCMsg_UserMessage) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

type CSVCMsgList_UserMessages struct {
	Usermsgs             []*CSVCMsgList_UserMessagesUsermsgT `protobuf:"bytes,1,rep,name=usermsgs" json:"usermsgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *CSVCMsgList_UserMessages) Reset()         { *m = CSVCMsgList_UserMessages{} }
func (m *CSVCMsgList_UserMessages) String() string { return proto.CompactTextString(m) }
func (*CSVCMsgList_UserMessages) ProtoMessage()    {}
func (*CSVCMsgList_UserMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{17}
}

func (m *CSVCMsgList_UserMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsgList_UserMessages.Unmarshal(m, b)
}
func (m *CSVCMsgList_UserMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsgList_UserMessages.Marshal(b, m, deterministic)
}
func (m *CSVCMsgList_UserMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsgList_UserMessages.Merge(m, src)
}
func (m *CSVCMsgList_UserMessages) XXX_Size() int {
	return xxx_messageInfo_CSVCMsgList_UserMessages.Size(m)
}
func (m *CSVCMsgList_UserMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsgList_UserMessages.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsgList_UserMessages proto.InternalMessageInfo

func (m *CSVCMsgList_UserMessages) GetUsermsgs() []*CSVCMsgList_UserMessagesUsermsgT {
	if m != nil {
		return m.Usermsgs
	}
	return nil
}

type CSVCMsgList_UserMessagesUsermsgT struct {
	Tick                 *int32               `protobuf:"varint,1,opt,name=tick" json:"tick,omitempty"`
	Msg                  *CSVCMsg_UserMessage `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CSVCMsgList_UserMessagesUsermsgT) Reset()         { *m = CSVCMsgList_UserMessagesUsermsgT{} }
func (m *CSVCMsgList_UserMessagesUsermsgT) String() string { return proto.CompactTextString(m) }
func (*CSVCMsgList_UserMessagesUsermsgT) ProtoMessage()    {}
func (*CSVCMsgList_UserMessagesUsermsgT) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{17, 0}
}

func (m *CSVCMsgList_UserMessagesUsermsgT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsgList_UserMessagesUsermsgT.Unmarshal(m, b)
}
func (m *CSVCMsgList_UserMessagesUsermsgT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsgList_UserMessagesUsermsgT.Marshal(b, m, deterministic)
}
func (m *CSVCMsgList_UserMessagesUsermsgT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsgList_UserMessagesUsermsgT.Merge(m, src)
}
func (m *CSVCMsgList_UserMessagesUsermsgT) XXX_Size() int {
	return xxx_messageInfo_CSVCMsgList_UserMessagesUsermsgT.Size(m)
}
func (m *CSVCMsgList_UserMessagesUsermsgT) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsgList_UserMessagesUsermsgT.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsgList_UserMessagesUsermsgT proto.InternalMessageInfo

func (m *CSVCMsgList_UserMessagesUsermsgT) GetTick() int32 {
	if m != nil && m.Tick != nil {
		return *m.Tick
	}
	return 0
}

func (m *CSVCMsgList_UserMessagesUsermsgT) GetMsg() *CSVCMsg_UserMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type CNETMsg_SpawnGroup_Load struct {
	Worldname              *string     `protobuf:"bytes,1,opt,name=worldname" json:"worldname,omitempty"`
	Entitylumpname         *string     `protobuf:"bytes,2,opt,name=entitylumpname" json:"entitylumpname,omitempty"`
	Entityfiltername       *string     `protobuf:"bytes,3,opt,name=entityfiltername" json:"entityfiltername,omitempty"`
	Spawngrouphandle       *uint32     `protobuf:"varint,4,opt,name=spawngrouphandle" json:"spawngrouphandle,omitempty"`
	Spawngroupownerhandle  *uint32     `protobuf:"varint,5,opt,name=spawngroupownerhandle" json:"spawngroupownerhandle,omitempty"`
	WorldOffsetPos         *CMsgVector `protobuf:"bytes,6,opt,name=world_offset_pos,json=worldOffsetPos" json:"world_offset_pos,omitempty"`
	WorldOffsetAngle       *CMsgQAngle `protobuf:"bytes,7,opt,name=world_offset_angle,json=worldOffsetAngle" json:"world_offset_angle,omitempty"`
	Spawngroupmanifest     []byte      `protobuf:"bytes,8,opt,name=spawngroupmanifest" json:"spawngroupmanifest,omitempty"`
	Flags                  *uint32     `protobuf:"varint,9,opt,name=flags" json:"flags,omitempty"`
	Tickcount              *int32      `protobuf:"varint,10,opt,name=tickcount" json:"tickcount,omitempty"`
	Manifestincomplete     *bool       `protobuf:"varint,11,opt,name=manifestincomplete" json:"manifestincomplete,omitempty"`
	Localnamefixup         *string     `protobuf:"bytes,12,opt,name=localnamefixup" json:"localnamefixup,omitempty"`
	Parentnamefixup        *string     `protobuf:"bytes,13,opt,name=parentnamefixup" json:"parentnamefixup,omitempty"`
	Manifestloadpriority   *int32      `protobuf:"varint,14,opt,name=manifestloadpriority" json:"manifestloadpriority,omitempty"`
	Worldgroupid           *uint32     `protobuf:"varint,15,opt,name=worldgroupid" json:"worldgroupid,omitempty"`
	Creationsequence       *uint32     `protobuf:"varint,16,opt,name=creationsequence" json:"creationsequence,omitempty"`
	Savegamefilename       *string     `protobuf:"bytes,17,opt,name=savegamefilename" json:"savegamefilename,omitempty"`
	Spawngroupparenthandle *uint32     `protobuf:"varint,18,opt,name=spawngroupparenthandle" json:"spawngroupparenthandle,omitempty"`
	Leveltransition        *bool       `protobuf:"varint,19,opt,name=leveltransition" json:"leveltransition,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}    `json:"-"`
	XXX_unrecognized       []byte      `json:"-"`
	XXX_sizecache          int32       `json:"-"`
}

func (m *CNETMsg_SpawnGroup_Load) Reset()         { *m = CNETMsg_SpawnGroup_Load{} }
func (m *CNETMsg_SpawnGroup_Load) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SpawnGroup_Load) ProtoMessage()    {}
func (*CNETMsg_SpawnGroup_Load) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{18}
}

func (m *CNETMsg_SpawnGroup_Load) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SpawnGroup_Load.Unmarshal(m, b)
}
func (m *CNETMsg_SpawnGroup_Load) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SpawnGroup_Load.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SpawnGroup_Load) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SpawnGroup_Load.Merge(m, src)
}
func (m *CNETMsg_SpawnGroup_Load) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SpawnGroup_Load.Size(m)
}
func (m *CNETMsg_SpawnGroup_Load) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SpawnGroup_Load.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SpawnGroup_Load proto.InternalMessageInfo

func (m *CNETMsg_SpawnGroup_Load) GetWorldname() string {
	if m != nil && m.Worldname != nil {
		return *m.Worldname
	}
	return ""
}

func (m *CNETMsg_SpawnGroup_Load) GetEntitylumpname() string {
	if m != nil && m.Entitylumpname != nil {
		return *m.Entitylumpname
	}
	return ""
}

func (m *CNETMsg_SpawnGroup_Load) GetEntityfiltername() string {
	if m != nil && m.Entityfiltername != nil {
		return *m.Entityfiltername
	}
	return ""
}

func (m *CNETMsg_SpawnGroup_Load) GetSpawngrouphandle() uint32 {
	if m != nil && m.Spawngrouphandle != nil {
		return *m.Spawngrouphandle
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetSpawngroupownerhandle() uint32 {
	if m != nil && m.Spawngroupownerhandle != nil {
		return *m.Spawngroupownerhandle
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetWorldOffsetPos() *CMsgVector {
	if m != nil {
		return m.WorldOffsetPos
	}
	return nil
}

func (m *CNETMsg_SpawnGroup_Load) GetWorldOffsetAngle() *CMsgQAngle {
	if m != nil {
		return m.WorldOffsetAngle
	}
	return nil
}

func (m *CNETMsg_SpawnGroup_Load) GetSpawngroupmanifest() []byte {
	if m != nil {
		return m.Spawngroupmanifest
	}
	return nil
}

func (m *CNETMsg_SpawnGroup_Load) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetTickcount() int32 {
	if m != nil && m.Tickcount != nil {
		return *m.Tickcount
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetManifestincomplete() bool {
	if m != nil && m.Manifestincomplete != nil {
		return *m.Manifestincomplete
	}
	return false
}

func (m *CNETMsg_SpawnGroup_Load) GetLocalnamefixup() string {
	if m != nil && m.Localnamefixup != nil {
		return *m.Localnamefixup
	}
	return ""
}

func (m *CNETMsg_SpawnGroup_Load) GetParentnamefixup() string {
	if m != nil && m.Parentnamefixup != nil {
		return *m.Parentnamefixup
	}
	return ""
}

func (m *CNETMsg_SpawnGroup_Load) GetManifestloadpriority() int32 {
	if m != nil && m.Manifestloadpriority != nil {
		return *m.Manifestloadpriority
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetWorldgroupid() uint32 {
	if m != nil && m.Worldgroupid != nil {
		return *m.Worldgroupid
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetCreationsequence() uint32 {
	if m != nil && m.Creationsequence != nil {
		return *m.Creationsequence
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetSavegamefilename() string {
	if m != nil && m.Savegamefilename != nil {
		return *m.Savegamefilename
	}
	return ""
}

func (m *CNETMsg_SpawnGroup_Load) GetSpawngroupparenthandle() uint32 {
	if m != nil && m.Spawngroupparenthandle != nil {
		return *m.Spawngroupparenthandle
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Load) GetLeveltransition() bool {
	if m != nil && m.Leveltransition != nil {
		return *m.Leveltransition
	}
	return false
}

type CNETMsg_SpawnGroup_ManifestUpdate struct {
	Spawngrouphandle     *uint32  `protobuf:"varint,1,opt,name=spawngrouphandle" json:"spawngrouphandle,omitempty"`
	Spawngroupmanifest   []byte   `protobuf:"bytes,2,opt,name=spawngroupmanifest" json:"spawngroupmanifest,omitempty"`
	Manifestincomplete   *bool    `protobuf:"varint,3,opt,name=manifestincomplete" json:"manifestincomplete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_SpawnGroup_ManifestUpdate) Reset()         { *m = CNETMsg_SpawnGroup_ManifestUpdate{} }
func (m *CNETMsg_SpawnGroup_ManifestUpdate) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SpawnGroup_ManifestUpdate) ProtoMessage()    {}
func (*CNETMsg_SpawnGroup_ManifestUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{19}
}

func (m *CNETMsg_SpawnGroup_ManifestUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SpawnGroup_ManifestUpdate.Unmarshal(m, b)
}
func (m *CNETMsg_SpawnGroup_ManifestUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SpawnGroup_ManifestUpdate.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SpawnGroup_ManifestUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SpawnGroup_ManifestUpdate.Merge(m, src)
}
func (m *CNETMsg_SpawnGroup_ManifestUpdate) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SpawnGroup_ManifestUpdate.Size(m)
}
func (m *CNETMsg_SpawnGroup_ManifestUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SpawnGroup_ManifestUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SpawnGroup_ManifestUpdate proto.InternalMessageInfo

func (m *CNETMsg_SpawnGroup_ManifestUpdate) GetSpawngrouphandle() uint32 {
	if m != nil && m.Spawngrouphandle != nil {
		return *m.Spawngrouphandle
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_ManifestUpdate) GetSpawngroupmanifest() []byte {
	if m != nil {
		return m.Spawngroupmanifest
	}
	return nil
}

func (m *CNETMsg_SpawnGroup_ManifestUpdate) GetManifestincomplete() bool {
	if m != nil && m.Manifestincomplete != nil {
		return *m.Manifestincomplete
	}
	return false
}

type CNETMsg_SpawnGroup_SetCreationTick struct {
	Spawngrouphandle     *uint32  `protobuf:"varint,1,opt,name=spawngrouphandle" json:"spawngrouphandle,omitempty"`
	Tickcount            *int32   `protobuf:"varint,2,opt,name=tickcount" json:"tickcount,omitempty"`
	Creationsequence     *uint32  `protobuf:"varint,3,opt,name=creationsequence" json:"creationsequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_SpawnGroup_SetCreationTick) Reset()         { *m = CNETMsg_SpawnGroup_SetCreationTick{} }
func (m *CNETMsg_SpawnGroup_SetCreationTick) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SpawnGroup_SetCreationTick) ProtoMessage()    {}
func (*CNETMsg_SpawnGroup_SetCreationTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{20}
}

func (m *CNETMsg_SpawnGroup_SetCreationTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SpawnGroup_SetCreationTick.Unmarshal(m, b)
}
func (m *CNETMsg_SpawnGroup_SetCreationTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SpawnGroup_SetCreationTick.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SpawnGroup_SetCreationTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SpawnGroup_SetCreationTick.Merge(m, src)
}
func (m *CNETMsg_SpawnGroup_SetCreationTick) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SpawnGroup_SetCreationTick.Size(m)
}
func (m *CNETMsg_SpawnGroup_SetCreationTick) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SpawnGroup_SetCreationTick.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SpawnGroup_SetCreationTick proto.InternalMessageInfo

func (m *CNETMsg_SpawnGroup_SetCreationTick) GetSpawngrouphandle() uint32 {
	if m != nil && m.Spawngrouphandle != nil {
		return *m.Spawngrouphandle
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_SetCreationTick) GetTickcount() int32 {
	if m != nil && m.Tickcount != nil {
		return *m.Tickcount
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_SetCreationTick) GetCreationsequence() uint32 {
	if m != nil && m.Creationsequence != nil {
		return *m.Creationsequence
	}
	return 0
}

type CNETMsg_SpawnGroup_Unload struct {
	Spawngrouphandle     *uint32  `protobuf:"varint,1,opt,name=spawngrouphandle" json:"spawngrouphandle,omitempty"`
	Flags                *uint32  `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
	Tickcount            *int32   `protobuf:"varint,3,opt,name=tickcount" json:"tickcount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_SpawnGroup_Unload) Reset()         { *m = CNETMsg_SpawnGroup_Unload{} }
func (m *CNETMsg_SpawnGroup_Unload) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SpawnGroup_Unload) ProtoMessage()    {}
func (*CNETMsg_SpawnGroup_Unload) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{21}
}

func (m *CNETMsg_SpawnGroup_Unload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SpawnGroup_Unload.Unmarshal(m, b)
}
func (m *CNETMsg_SpawnGroup_Unload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SpawnGroup_Unload.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SpawnGroup_Unload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SpawnGroup_Unload.Merge(m, src)
}
func (m *CNETMsg_SpawnGroup_Unload) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SpawnGroup_Unload.Size(m)
}
func (m *CNETMsg_SpawnGroup_Unload) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SpawnGroup_Unload.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SpawnGroup_Unload proto.InternalMessageInfo

func (m *CNETMsg_SpawnGroup_Unload) GetSpawngrouphandle() uint32 {
	if m != nil && m.Spawngrouphandle != nil {
		return *m.Spawngrouphandle
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Unload) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CNETMsg_SpawnGroup_Unload) GetTickcount() int32 {
	if m != nil && m.Tickcount != nil {
		return *m.Tickcount
	}
	return 0
}

type CNETMsg_SpawnGroup_LoadCompleted struct {
	Spawngrouphandle     *uint32  `protobuf:"varint,1,opt,name=spawngrouphandle" json:"spawngrouphandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNETMsg_SpawnGroup_LoadCompleted) Reset()         { *m = CNETMsg_SpawnGroup_LoadCompleted{} }
func (m *CNETMsg_SpawnGroup_LoadCompleted) String() string { return proto.CompactTextString(m) }
func (*CNETMsg_SpawnGroup_LoadCompleted) ProtoMessage()    {}
func (*CNETMsg_SpawnGroup_LoadCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{22}
}

func (m *CNETMsg_SpawnGroup_LoadCompleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNETMsg_SpawnGroup_LoadCompleted.Unmarshal(m, b)
}
func (m *CNETMsg_SpawnGroup_LoadCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNETMsg_SpawnGroup_LoadCompleted.Marshal(b, m, deterministic)
}
func (m *CNETMsg_SpawnGroup_LoadCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNETMsg_SpawnGroup_LoadCompleted.Merge(m, src)
}
func (m *CNETMsg_SpawnGroup_LoadCompleted) XXX_Size() int {
	return xxx_messageInfo_CNETMsg_SpawnGroup_LoadCompleted.Size(m)
}
func (m *CNETMsg_SpawnGroup_LoadCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_CNETMsg_SpawnGroup_LoadCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_CNETMsg_SpawnGroup_LoadCompleted proto.InternalMessageInfo

func (m *CNETMsg_SpawnGroup_LoadCompleted) GetSpawngrouphandle() uint32 {
	if m != nil && m.Spawngrouphandle != nil {
		return *m.Spawngrouphandle
	}
	return 0
}

type CSVCMsg_GameSessionConfiguration struct {
	IsMultiplayer        *bool    `protobuf:"varint,1,opt,name=is_multiplayer,json=isMultiplayer" json:"is_multiplayer,omitempty"`
	IsLoadsavegame       *bool    `protobuf:"varint,2,opt,name=is_loadsavegame,json=isLoadsavegame" json:"is_loadsavegame,omitempty"`
	IsBackgroundMap      *bool    `protobuf:"varint,3,opt,name=is_background_map,json=isBackgroundMap" json:"is_background_map,omitempty"`
	IsHeadless           *bool    `protobuf:"varint,4,opt,name=is_headless,json=isHeadless" json:"is_headless,omitempty"`
	MinClientLimit       *uint32  `protobuf:"varint,5,opt,name=min_client_limit,json=minClientLimit" json:"min_client_limit,omitempty"`
	MaxClientLimit       *uint32  `protobuf:"varint,6,opt,name=max_client_limit,json=maxClientLimit" json:"max_client_limit,omitempty"`
	MaxClients           *uint32  `protobuf:"varint,7,opt,name=max_clients,json=maxClients" json:"max_clients,omitempty"`
	TickInterval         *uint32  `protobuf:"fixed32,8,opt,name=tick_interval,json=tickInterval" json:"tick_interval,omitempty"`
	Hostname             *string  `protobuf:"bytes,9,opt,name=hostname" json:"hostname,omitempty"`
	Savegamename         *string  `protobuf:"bytes,10,opt,name=savegamename" json:"savegamename,omitempty"`
	S1Mapname            *string  `protobuf:"bytes,11,opt,name=s1_mapname,json=s1Mapname" json:"s1_mapname,omitempty"`
	Gamemode             *string  `protobuf:"bytes,12,opt,name=gamemode" json:"gamemode,omitempty"`
	ServerIpAddress      *string  `protobuf:"bytes,13,opt,name=server_ip_address,json=serverIpAddress" json:"server_ip_address,omitempty"`
	Data                 []byte   `protobuf:"bytes,14,opt,name=data" json:"data,omitempty"`
	IsLocalonly          *bool    `protobuf:"varint,15,opt,name=is_localonly,json=isLocalonly" json:"is_localonly,omitempty"`
	NoSteamServer        *bool    `protobuf:"varint,19,opt,name=no_steam_server,json=noSteamServer" json:"no_steam_server,omitempty"`
	IsTransition         *bool    `protobuf:"varint,16,opt,name=is_transition,json=isTransition" json:"is_transition,omitempty"`
	Previouslevel        *string  `protobuf:"bytes,17,opt,name=previouslevel" json:"previouslevel,omitempty"`
	Landmarkname         *string  `protobuf:"bytes,18,opt,name=landmarkname" json:"landmarkname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSVCMsg_GameSessionConfiguration) Reset()         { *m = CSVCMsg_GameSessionConfiguration{} }
func (m *CSVCMsg_GameSessionConfiguration) String() string { return proto.CompactTextString(m) }
func (*CSVCMsg_GameSessionConfiguration) ProtoMessage()    {}
func (*CSVCMsg_GameSessionConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_af562a66c2afa27a, []int{23}
}

func (m *CSVCMsg_GameSessionConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSVCMsg_GameSessionConfiguration.Unmarshal(m, b)
}
func (m *CSVCMsg_GameSessionConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSVCMsg_GameSessionConfiguration.Marshal(b, m, deterministic)
}
func (m *CSVCMsg_GameSessionConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSVCMsg_GameSessionConfiguration.Merge(m, src)
}
func (m *CSVCMsg_GameSessionConfiguration) XXX_Size() int {
	return xxx_messageInfo_CSVCMsg_GameSessionConfiguration.Size(m)
}
func (m *CSVCMsg_GameSessionConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_CSVCMsg_GameSessionConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_CSVCMsg_GameSessionConfiguration proto.InternalMessageInfo

func (m *CSVCMsg_GameSessionConfiguration) GetIsMultiplayer() bool {
	if m != nil && m.IsMultiplayer != nil {
		return *m.IsMultiplayer
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetIsLoadsavegame() bool {
	if m != nil && m.IsLoadsavegame != nil {
		return *m.IsLoadsavegame
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetIsBackgroundMap() bool {
	if m != nil && m.IsBackgroundMap != nil {
		return *m.IsBackgroundMap
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetIsHeadless() bool {
	if m != nil && m.IsHeadless != nil {
		return *m.IsHeadless
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetMinClientLimit() uint32 {
	if m != nil && m.MinClientLimit != nil {
		return *m.MinClientLimit
	}
	return 0
}

func (m *CSVCMsg_GameSessionConfiguration) GetMaxClientLimit() uint32 {
	if m != nil && m.MaxClientLimit != nil {
		return *m.MaxClientLimit
	}
	return 0
}

func (m *CSVCMsg_GameSessionConfiguration) GetMaxClients() uint32 {
	if m != nil && m.MaxClients != nil {
		return *m.MaxClients
	}
	return 0
}

func (m *CSVCMsg_GameSessionConfiguration) GetTickInterval() uint32 {
	if m != nil && m.TickInterval != nil {
		return *m.TickInterval
	}
	return 0
}

func (m *CSVCMsg_GameSessionConfiguration) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *CSVCMsg_GameSessionConfiguration) GetSavegamename() string {
	if m != nil && m.Savegamename != nil {
		return *m.Savegamename
	}
	return ""
}

func (m *CSVCMsg_GameSessionConfiguration) GetS1Mapname() string {
	if m != nil && m.S1Mapname != nil {
		return *m.S1Mapname
	}
	return ""
}

func (m *CSVCMsg_GameSessionConfiguration) GetGamemode() string {
	if m != nil && m.Gamemode != nil {
		return *m.Gamemode
	}
	return ""
}

func (m *CSVCMsg_GameSessionConfiguration) GetServerIpAddress() string {
	if m != nil && m.ServerIpAddress != nil {
		return *m.ServerIpAddress
	}
	return ""
}

func (m *CSVCMsg_GameSessionConfiguration) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CSVCMsg_GameSessionConfiguration) GetIsLocalonly() bool {
	if m != nil && m.IsLocalonly != nil {
		return *m.IsLocalonly
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetNoSteamServer() bool {
	if m != nil && m.NoSteamServer != nil {
		return *m.NoSteamServer
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetIsTransition() bool {
	if m != nil && m.IsTransition != nil {
		return *m.IsTransition
	}
	return false
}

func (m *CSVCMsg_GameSessionConfiguration) GetPreviouslevel() string {
	if m != nil && m.Previouslevel != nil {
		return *m.Previouslevel
	}
	return ""
}

func (m *CSVCMsg_GameSessionConfiguration) GetLandmarkname() string {
	if m != nil && m.Landmarkname != nil {
		return *m.Landmarkname
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.NET_Messages", NET_Messages_name, NET_Messages_value)
	proto.RegisterEnum("protocol.SpawnGroupFlagsT", SpawnGroupFlagsT_name, SpawnGroupFlagsT_value)
	proto.RegisterType((*CMsgVector)(nil), "protocol.CMsgVector")
	proto.RegisterType((*CMsgVector2D)(nil), "protocol.CMsgVector2D")
	proto.RegisterType((*CMsgQAngle)(nil), "protocol.CMsgQAngle")
	proto.RegisterType((*CMsgRGBA)(nil), "protocol.CMsgRGBA")
	proto.RegisterType((*CMsgPlayerInfo)(nil), "protocol.CMsgPlayerInfo")
	proto.RegisterType((*CEntityMsg)(nil), "protocol.CEntityMsg")
	proto.RegisterType((*CMsg_CVars)(nil), "protocol.CMsg_CVars")
	proto.RegisterType((*CMsg_CVars_CVar)(nil), "protocol.CMsg_CVars.CVar")
	proto.RegisterType((*CNETMsg_NOP)(nil), "protocol.CNETMsg_NOP")
	proto.RegisterType((*CNETMsg_SplitScreenUser)(nil), "protocol.CNETMsg_SplitScreenUser")
	proto.RegisterType((*CNETMsg_Disconnect)(nil), "protocol.CNETMsg_Disconnect")
	proto.RegisterType((*CNETMsg_Tick)(nil), "protocol.CNETMsg_Tick")
	proto.RegisterType((*CNETMsg_StringCmd)(nil), "protocol.CNETMsg_StringCmd")
	proto.RegisterType((*CNETMsg_SetConVar)(nil), "protocol.CNETMsg_SetConVar")
	proto.RegisterType((*CNETMsg_SignonState)(nil), "protocol.CNETMsg_SignonState")
	proto.RegisterType((*CSVCMsg_GameEvent)(nil), "protocol.CSVCMsg_GameEvent")
	proto.RegisterType((*CSVCMsg_GameEventKeyT)(nil), "protocol.CSVCMsg_GameEvent.key_t")
	proto.RegisterType((*CSVCMsgList_GameEvents)(nil), "protocol.CSVCMsgList_GameEvents")
	proto.RegisterType((*CSVCMsgList_GameEventsEventT)(nil), "protocol.CSVCMsgList_GameEvents.event_t")
	proto.RegisterType((*CSVCMsg_UserMessage)(nil), "protocol.CSVCMsg_UserMessage")
	proto.RegisterType((*CSVCMsgList_UserMessages)(nil), "protocol.CSVCMsgList_UserMessages")
	proto.RegisterType((*CSVCMsgList_UserMessagesUsermsgT)(nil), "protocol.CSVCMsgList_UserMessages.usermsg_t")
	proto.RegisterType((*CNETMsg_SpawnGroup_Load)(nil), "protocol.CNETMsg_SpawnGroup_Load")
	proto.RegisterType((*CNETMsg_SpawnGroup_ManifestUpdate)(nil), "protocol.CNETMsg_SpawnGroup_ManifestUpdate")
	proto.RegisterType((*CNETMsg_SpawnGroup_SetCreationTick)(nil), "protocol.CNETMsg_SpawnGroup_SetCreationTick")
	proto.RegisterType((*CNETMsg_SpawnGroup_Unload)(nil), "protocol.CNETMsg_SpawnGroup_Unload")
	proto.RegisterType((*CNETMsg_SpawnGroup_LoadCompleted)(nil), "protocol.CNETMsg_SpawnGroup_LoadCompleted")
	proto.RegisterType((*CSVCMsg_GameSessionConfiguration)(nil), "protocol.CSVCMsg_GameSessionConfiguration")
}

func init() {
	proto.RegisterFile("networkbasetypes.proto", fileDescriptor_af562a66c2afa27a)
}

var fileDescriptor_af562a66c2afa27a = []byte{
	// 2151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xc1, 0x72, 0x1b, 0xb9,
	0xd1, 0xde, 0x91, 0x44, 0x89, 0x6c, 0x92, 0xd2, 0x08, 0xf2, 0x7a, 0x69, 0xed, 0xae, 0x2d, 0x8f,
	0xd7, 0xb6, 0xca, 0xff, 0x5a, 0xfb, 0x5b, 0xb5, 0xf1, 0x21, 0x87, 0x64, 0x29, 0x8a, 0xb6, 0x59,
	0xa6, 0x48, 0x65, 0x48, 0xd9, 0xe5, 0x13, 0x0a, 0xe6, 0x40, 0x34, 0x4a, 0x33, 0x03, 0x66, 0x00,
	0xd2, 0xd2, 0xe6, 0xe2, 0xe7, 0xc8, 0x31, 0xe7, 0x54, 0x72, 0xcb, 0x53, 0xa4, 0xf2, 0x14, 0xb9,
	0x6c, 0x8e, 0x79, 0x82, 0x14, 0x7a, 0x30, 0xe4, 0x90, 0xa2, 0xb6, 0xca, 0x17, 0x89, 0xfd, 0xf5,
	0xd7, 0x0d, 0xa0, 0xbb, 0xd1, 0xe8, 0x81, 0xdb, 0x31, 0xd7, 0x1f, 0x65, 0x72, 0xf1, 0x9e, 0x29,
	0xae, 0xaf, 0x46, 0x5c, 0x1d, 0x8c, 0x12, 0xa9, 0x25, 0x29, 0xe2, 0xbf, 0x81, 0x0c, 0x77, 0x6b,
	0x96, 0x41, 0x07, 0x32, 0x8e, 0xf9, 0x40, 0x0b, 0x19, 0xa7, 0x1c, 0xef, 0x39, 0x40, 0xe3, 0x44,
	0x0d, 0xdf, 0xf0, 0x81, 0x96, 0x09, 0xa9, 0x80, 0x73, 0x59, 0x73, 0xf6, 0x9c, 0xfd, 0x15, 0xdf,
	0xb9, 0x34, 0xd2, 0x55, 0x6d, 0x25, 0x95, 0xae, 0x8c, 0xf4, 0x73, 0x6d, 0x35, 0x95, 0x7e, 0xf6,
	0x9e, 0x40, 0x65, 0x66, 0x77, 0x78, 0xfc, 0x6b, 0x96, 0xd9, 0x1a, 0x7f, 0xa8, 0xc7, 0xc3, 0x90,
	0x7f, 0xc6, 0x1a, 0x47, 0x50, 0x34, 0x76, 0xfe, 0xcb, 0xa3, 0xba, 0xd1, 0x24, 0x68, 0x55, 0xf0,
	0x1d, 0xdc, 0xe7, 0x10, 0xad, 0x0a, 0xbe, 0x33, 0x34, 0xd2, 0x7b, 0xb4, 0x2a, 0xf8, 0xce, 0x7b,
	0x23, 0xb1, 0xda, 0x5a, 0x2a, 0x31, 0xef, 0x2f, 0x0e, 0x6c, 0x1a, 0x27, 0xa7, 0x21, 0xbb, 0xe2,
	0x49, 0x2b, 0x3e, 0x97, 0x84, 0xc0, 0x5a, 0xcc, 0x22, 0x8e, 0xde, 0x4a, 0x3e, 0xfe, 0x36, 0xd8,
	0xe5, 0x58, 0x04, 0xe8, 0x73, 0xdd, 0xc7, 0xdf, 0xe4, 0x36, 0xac, 0x8f, 0x15, 0x4f, 0x44, 0x60,
	0x7d, 0x5b, 0x89, 0xd4, 0x60, 0x43, 0x69, 0xce, 0x22, 0x11, 0xe0, 0x32, 0xeb, 0x7e, 0x26, 0x92,
	0xbb, 0x00, 0xe7, 0xec, 0x82, 0x8f, 0x70, 0xad, 0x5a, 0x61, 0xcf, 0xd9, 0x2f, 0xfa, 0x39, 0xc4,
	0x78, 0x14, 0xea, 0x43, 0xa8, 0x27, 0xb5, 0x75, 0xd4, 0x59, 0xc9, 0x7b, 0x06, 0xd0, 0x68, 0xc6,
	0x5a, 0xe8, 0xab, 0x13, 0x35, 0x24, 0x0f, 0xa0, 0xaa, 0x59, 0x32, 0xe4, 0x9a, 0x72, 0xc4, 0x70,
	0xa3, 0x55, 0xbf, 0x92, 0x82, 0x29, 0xcf, 0x93, 0x69, 0x4c, 0x69, 0xe3, 0x0d, 0x4b, 0x14, 0xf9,
	0x01, 0x0a, 0x83, 0x09, 0x4b, 0x54, 0xcd, 0xd9, 0x5b, 0xdd, 0x2f, 0x1f, 0xde, 0x39, 0xc8, 0x32,
	0x7f, 0x30, 0x23, 0x1d, 0x98, 0xbf, 0x7e, 0xca, 0xdb, 0xfd, 0x7f, 0x58, 0x33, 0xe2, 0xd2, 0x58,
	0xdc, 0x82, 0xc2, 0x84, 0x85, 0x63, 0x8e, 0xc1, 0x28, 0xf9, 0xa9, 0xe0, 0x55, 0xa1, 0xdc, 0xe8,
	0x34, 0xfb, 0xc6, 0x5d, 0xa7, 0x7b, 0xea, 0x3d, 0x85, 0xaf, 0x32, 0xb1, 0x37, 0x0a, 0x85, 0xee,
	0x0d, 0x12, 0xce, 0xe3, 0x33, 0xc5, 0xd1, 0xa7, 0x0a, 0xa5, 0xb6, 0xd9, 0xc2, 0xdf, 0x9e, 0x04,
	0x92, 0xd1, 0x8f, 0x85, 0xb2, 0x55, 0x48, 0xde, 0xc1, 0x7a, 0xc2, 0x99, 0x92, 0x31, 0x2e, 0xb5,
	0x79, 0xf8, 0x70, 0xb6, 0xef, 0x66, 0x27, 0xad, 0xd8, 0x19, 0x5b, 0xc8, 0xd8, 0x47, 0xf2, 0x6f,
	0x77, 0x3b, 0xcd, 0xfe, 0xdb, 0xae, 0xff, 0x9a, 0x1e, 0xb7, 0x7a, 0x8d, 0x6e, 0xa7, 0xd3, 0x6c,
	0xf4, 0x69, 0xab, 0xf3, 0xa6, 0xde, 0x6e, 0x1d, 0xfb, 0xd6, 0xa1, 0xf7, 0xdf, 0x15, 0xa8, 0x64,
	0x2b, 0xf6, 0xc5, 0xe0, 0xc2, 0xec, 0x4a, 0x8b, 0xc1, 0x85, 0x0d, 0x26, 0xfe, 0x26, 0x0f, 0x61,
	0xf3, 0x83, 0x54, 0x9a, 0x9e, 0x27, 0x2c, 0xe2, 0x5a, 0x44, 0xe9, 0x91, 0xab, 0x7e, 0xd5, 0xa0,
	0x2f, 0x32, 0x90, 0xfc, 0x1e, 0xbe, 0x99, 0xa7, 0x51, 0xa5, 0x03, 0x1a, 0xf0, 0x89, 0x60, 0x66,
	0x57, 0x58, 0x1e, 0x55, 0xff, 0xce, 0x9c, 0x51, 0x4f, 0x07, 0xc7, 0x19, 0x81, 0x3c, 0x83, 0x5b,
	0xe8, 0x60, 0x20, 0xa3, 0xd1, 0x58, 0x23, 0x86, 0xab, 0xad, 0xa1, 0xe1, 0x8e, 0xd1, 0x35, 0xe6,
	0x55, 0xe4, 0x35, 0x78, 0xcb, 0x4c, 0x16, 0x56, 0x2e, 0xa0, 0x83, 0x7b, 0x4b, 0x1c, 0xcc, 0xad,
	0xdf, 0x82, 0xfb, 0xb3, 0x03, 0x28, 0xcd, 0x12, 0xbd, 0xc4, 0xd7, 0x3a, 0xfa, 0xba, 0x3b, 0x3d,
	0xc5, 0x94, 0x37, 0xe7, 0xea, 0x6b, 0x28, 0xa1, 0xab, 0x50, 0x2a, 0x55, 0xdb, 0x40, 0x93, 0xa2,
	0x01, 0xda, 0x52, 0x29, 0xef, 0x29, 0x6c, 0x4f, 0x8b, 0x42, 0x27, 0x22, 0x1e, 0x36, 0x22, 0xbc,
	0x2e, 0x03, 0x19, 0x45, 0x2c, 0x0e, 0x6c, 0x95, 0x65, 0xa2, 0xd7, 0xc8, 0xd1, 0xb9, 0x6e, 0xc8,
	0xd8, 0x54, 0xe4, 0x81, 0xa1, 0xc7, 0xb6, 0x98, 0x9d, 0xfd, 0xf2, 0xe1, 0xad, 0x65, 0xc5, 0xec,
	0x67, 0x24, 0xef, 0x17, 0x07, 0x76, 0xa6, 0x5e, 0xc4, 0x30, 0x96, 0x71, 0x4f, 0x33, 0xcd, 0xc9,
	0x7d, 0xa8, 0x28, 0x14, 0xa9, 0x32, 0xb2, 0xcd, 0x7b, 0x59, 0xe5, 0x28, 0xf7, 0xa0, 0xac, 0x46,
	0xec, 0x63, 0x4c, 0x07, 0x72, 0x1c, 0x6b, 0x9b, 0x7b, 0x40, 0xa8, 0x61, 0x10, 0xf2, 0x3d, 0x90,
	0x78, 0x1c, 0x51, 0xc5, 0x93, 0x09, 0x4f, 0x68, 0x7a, 0x89, 0x95, 0x4d, 0xb7, 0x1b, 0x8f, 0xa3,
	0x1e, 0x2a, 0xd2, 0xd6, 0xa2, 0xc8, 0x53, 0x20, 0x96, 0x42, 0x6d, 0xbb, 0x15, 0x81, 0xaa, 0xad,
	0xed, 0xad, 0xee, 0x97, 0xfc, 0x6d, 0xab, 0xe9, 0x4c, 0x15, 0xe4, 0x0e, 0x14, 0x23, 0x36, 0xa2,
	0x78, 0xfd, 0x0a, 0x69, 0x60, 0x22, 0x36, 0xea, 0x98, 0x1b, 0x78, 0x1b, 0xd6, 0x59, 0x10, 0xc8,
	0x58, 0x61, 0x52, 0x4a, 0xbe, 0x95, 0xbc, 0xff, 0xac, 0xc0, 0x76, 0xa3, 0xf7, 0x06, 0xc3, 0xf0,
	0x92, 0x45, 0xbc, 0x39, 0xe1, 0xb1, 0x26, 0xdf, 0x02, 0x70, 0xf3, 0x83, 0xe6, 0x6e, 0x72, 0x09,
	0x11, 0x74, 0x56, 0x83, 0x0d, 0x14, 0x6c, 0x77, 0x2b, 0xf8, 0x99, 0x48, 0x7e, 0x03, 0x6b, 0x17,
	0xfc, 0xca, 0x1c, 0xc8, 0x34, 0x8d, 0xfb, 0xb9, 0x38, 0x2f, 0xae, 0x71, 0x70, 0xc1, 0xaf, 0xa8,
	0xf6, 0x91, 0xbe, 0xfb, 0x6f, 0x07, 0x0a, 0x28, 0xe3, 0x9d, 0xba, 0x1a, 0xf1, 0xec, 0xa6, 0x9b,
	0xdf, 0x66, 0x37, 0x13, 0x16, 0x52, 0x85, 0xf9, 0xb7, 0x2d, 0xa4, 0x34, 0x61, 0x61, 0x5a, 0x10,
	0xa6, 0x7e, 0x8c, 0xfa, 0x3c, 0x94, 0x4c, 0xdb, 0x4e, 0x5f, 0x9c, 0xb0, 0xf0, 0x85, 0x91, 0x4d,
	0x48, 0x8c, 0x32, 0x94, 0xf1, 0xd0, 0x76, 0xf0, 0x8d, 0x09, 0x0b, 0xdb, 0x72, 0x66, 0xa7, 0x3e,
	0xc8, 0x44, 0x63, 0xb8, 0x0a, 0x68, 0xd7, 0x33, 0x72, 0x66, 0xf7, 0xfe, 0x4a, 0x73, 0x8c, 0x58,
	0x6a, 0x77, 0x74, 0xa5, 0xf9, 0x54, 0x25, 0x65, 0x88, 0xe5, 0x5a, 0x4c, 0x55, 0x52, 0x86, 0xd9,
	0x4e, 0xc7, 0x22, 0xd6, 0xcf, 0x7f, 0xac, 0x15, 0xf7, 0x9c, 0xfd, 0x35, 0xdc, 0xe9, 0x19, 0x02,
	0xde, 0x5f, 0x1d, 0xb8, 0x6d, 0x03, 0xd1, 0x16, 0x4a, 0xcf, 0x82, 0xa1, 0xc8, 0x4f, 0xb0, 0x8e,
	0x31, 0xcc, 0xfa, 0xed, 0xfe, 0xb5, 0xd0, 0x2d, 0x58, 0x1c, 0xa4, 0x09, 0xd2, 0xbe, 0xb5, 0xdb,
	0x3d, 0xb5, 0x49, 0xb1, 0x41, 0xcc, 0x1a, 0x53, 0xc1, 0x36, 0xa6, 0x67, 0x50, 0x40, 0x35, 0xc6,
	0xaf, 0x7c, 0xf8, 0xf5, 0xaf, 0xa4, 0xc6, 0x4f, 0x99, 0xde, 0x6b, 0xd8, 0xc9, 0x74, 0xa6, 0x0b,
	0x9f, 0x70, 0xa5, 0xd8, 0x10, 0xcf, 0x1f, 0xa9, 0x21, 0xcd, 0xa5, 0x69, 0x23, 0x52, 0xc3, 0xbe,
	0xc9, 0x94, 0x55, 0x05, 0x4c, 0x33, 0x5c, 0xa7, 0x82, 0xaa, 0x63, 0xa6, 0x99, 0xf7, 0x0f, 0x07,
	0x6a, 0xf9, 0x93, 0xe4, 0x3c, 0x2a, 0xf2, 0x0a, 0x8a, 0xe6, 0x25, 0x8c, 0xd4, 0x30, 0x3b, 0xff,
	0xf7, 0xcb, 0xcf, 0x9f, 0xb7, 0x3a, 0xb0, 0x26, 0x54, 0xfb, 0x53, 0xeb, 0xdd, 0x53, 0x28, 0x4d,
	0xe1, 0xa5, 0x71, 0xf8, 0x01, 0x56, 0x23, 0x35, 0xb4, 0x51, 0xf8, 0xf6, 0x7a, 0x14, 0x72, 0x2b,
	0xf8, 0x86, 0xe9, 0xfd, 0xb2, 0x9e, 0x7f, 0x97, 0xd8, 0xc7, 0xf8, 0x65, 0x22, 0xc7, 0x23, 0xda,
	0x96, 0x2c, 0x20, 0xdf, 0x40, 0xe9, 0xa3, 0x4c, 0xc2, 0x20, 0x7f, 0x4d, 0xa6, 0x00, 0x79, 0x04,
	0x9b, 0xe9, 0x73, 0x1b, 0x8e, 0xa3, 0x11, 0x52, 0xd2, 0xda, 0x5d, 0x40, 0xc9, 0x13, 0x70, 0x53,
	0xe4, 0x5c, 0x84, 0x9a, 0x27, 0xc8, 0x5c, 0x45, 0xe6, 0x35, 0xdc, 0x70, 0xb1, 0x9b, 0x0c, 0xcd,
	0x26, 0x3e, 0xb0, 0x38, 0x08, 0xb3, 0x9e, 0x7f, 0x0d, 0x27, 0x3f, 0xc2, 0x97, 0x33, 0x4c, 0x7e,
	0x8c, 0x79, 0x62, 0x0d, 0xd2, 0x1e, 0xbf, 0x5c, 0x49, 0x7e, 0x07, 0x2e, 0x1e, 0x81, 0xca, 0xf3,
	0x73, 0xc5, 0x35, 0x1d, 0xc9, 0xb4, 0x67, 0x5c, 0x6b, 0x9b, 0xe9, 0xa0, 0xe6, 0x6f, 0x22, 0xbb,
	0x8b, 0xe4, 0x53, 0xa9, 0xc8, 0x11, 0x90, 0x39, 0x7b, 0x66, 0x46, 0x34, 0xbc, 0x28, 0xd7, 0x3c,
	0xa4, 0xe3, 0x9b, 0xef, 0xe6, 0x3c, 0xa4, 0x03, 0xdd, 0x01, 0x90, 0xd9, 0xe6, 0x22, 0x16, 0x8b,
	0x73, 0xae, 0x34, 0xde, 0xa7, 0x8a, 0xbf, 0x44, 0x63, 0xe6, 0x8b, 0xf3, 0x90, 0x0d, 0x55, 0xad,
	0x84, 0x27, 0x4b, 0x05, 0x93, 0x1d, 0x93, 0xf2, 0xb4, 0x15, 0x03, 0xd6, 0xc0, 0x0c, 0x30, 0x6b,
	0x64, 0xf6, 0x22, 0x36, 0x6f, 0x62, 0xc8, 0x35, 0xaf, 0x95, 0xf1, 0x42, 0x2f, 0xd1, 0x98, 0x6c,
	0x86, 0x72, 0xc0, 0x42, 0x93, 0x86, 0x73, 0x71, 0x39, 0x1e, 0xd5, 0x2a, 0x69, 0x36, 0xe7, 0x51,
	0xb2, 0x0f, 0x5b, 0x23, 0x96, 0xf0, 0x58, 0xcf, 0x88, 0x55, 0x24, 0x2e, 0xc2, 0xe4, 0x10, 0x6e,
	0x65, 0xeb, 0x84, 0x92, 0x05, 0xa3, 0x44, 0xc8, 0xc4, 0x0c, 0x67, 0x9b, 0xb8, 0xd5, 0xa5, 0x3a,
	0xe2, 0x41, 0x05, 0xa3, 0x85, 0xe7, 0x17, 0x41, 0x6d, 0x2b, 0x1d, 0xe4, 0xf2, 0x98, 0xa9, 0x91,
	0x41, 0xc2, 0xf1, 0x71, 0x55, 0xfc, 0x8f, 0x63, 0x1e, 0x0f, 0x78, 0xcd, 0x4d, 0x6b, 0x64, 0x11,
	0xc7, 0x7a, 0x62, 0x13, 0x3e, 0xc4, 0x4d, 0x85, 0x1c, 0x6b, 0x6f, 0x3b, 0xad, 0xbd, 0x45, 0x9c,
	0x3c, 0x87, 0xdb, 0xb3, 0xd8, 0xa7, 0x87, 0xb1, 0x05, 0x45, 0xd0, 0xfb, 0x0d, 0x5a, 0x13, 0x91,
	0x90, 0x4f, 0x78, 0xa8, 0x13, 0x16, 0x2b, 0x81, 0x93, 0xc1, 0x0e, 0x86, 0x79, 0x11, 0xf6, 0xfe,
	0xee, 0xc0, 0xfd, 0x25, 0x77, 0xed, 0xc4, 0x46, 0xe2, 0x6c, 0x14, 0x98, 0x47, 0x76, 0xd9, 0x1d,
	0x70, 0x6e, 0xb8, 0x03, 0xcb, 0x2b, 0x69, 0xe5, 0xc6, 0x4a, 0x5a, 0x5e, 0x15, 0xab, 0x37, 0x55,
	0x85, 0xf7, 0x67, 0x07, 0xbc, 0x25, 0x3b, 0x36, 0xc3, 0x87, 0x0d, 0x35, 0x8e, 0x8a, 0x9f, 0xb3,
	0xe5, 0xb9, 0xb2, 0x5d, 0x59, 0x2c, 0xdb, 0x65, 0xc9, 0x5d, 0x5d, 0x9e, 0x5c, 0xef, 0x4f, 0x70,
	0x67, 0xc9, 0xde, 0xce, 0x62, 0x53, 0x51, 0x9f, 0xb5, 0xa5, 0xe9, 0xfd, 0x5a, 0xb9, 0xf1, 0x7e,
	0xad, 0x2e, 0x6c, 0xd4, 0xeb, 0xc0, 0xde, 0x0d, 0x6d, 0xb3, 0x61, 0x83, 0xf7, 0x59, 0x7b, 0xf0,
	0xfe, 0x55, 0x80, 0xbd, 0xfc, 0x53, 0xd5, 0xe3, 0x4a, 0x09, 0x19, 0x37, 0x64, 0x7c, 0x2e, 0x86,
	0xe3, 0x24, 0x9d, 0x25, 0x1f, 0xc2, 0xa6, 0x50, 0x34, 0x1a, 0x87, 0x5a, 0xd8, 0x4f, 0x26, 0x07,
	0x53, 0x57, 0x15, 0xea, 0x64, 0x06, 0x92, 0xc7, 0xb0, 0x25, 0x14, 0x35, 0x61, 0xc8, 0x8a, 0x1c,
	0x4f, 0x56, 0xf4, 0x37, 0x85, 0x6a, 0xe7, 0x50, 0xf2, 0x04, 0xb6, 0x85, 0xa2, 0xef, 0xd9, 0xe0,
	0xc2, 0x6c, 0x25, 0x0e, 0x68, 0xc4, 0x46, 0xb6, 0x1a, 0xb6, 0x84, 0x3a, 0x9a, 0xe2, 0x27, 0x6c,
	0x64, 0x66, 0x3f, 0xa1, 0xe8, 0x07, 0xce, 0x82, 0x90, 0x2b, 0x85, 0x5d, 0xb9, 0xe8, 0x83, 0x50,
	0xaf, 0x2c, 0x42, 0xf6, 0xc1, 0x8d, 0x44, 0x4c, 0x07, 0xa1, 0x30, 0xcf, 0x74, 0x28, 0x22, 0xa1,
	0x6d, 0x2b, 0xde, 0x8c, 0x44, 0xdc, 0x40, 0xb8, 0x6d, 0x50, 0x64, 0xb2, 0xcb, 0x79, 0xe6, 0xba,
	0x65, 0xb2, 0xcb, 0x3c, 0xf3, 0x1e, 0x94, 0x67, 0xcc, 0x6c, 0x7c, 0x86, 0x29, 0x49, 0xe1, 0xa7,
	0x9f, 0x18, 0x5c, 0x50, 0x11, 0x6b, 0x9e, 0x4c, 0x58, 0x88, 0x5d, 0x74, 0xc3, 0xaf, 0x18, 0xb0,
	0x65, 0x31, 0xb2, 0x0b, 0x38, 0x71, 0xe3, 0xed, 0x2f, 0xe1, 0xed, 0x9f, 0xca, 0xa6, 0xe3, 0x64,
	0xe1, 0x40, 0x3d, 0xa0, 0x7e, 0x0e, 0x33, 0x73, 0x8f, 0x7a, 0x66, 0x62, 0x83, 0x8c, 0x72, 0xfa,
	0x10, 0xaa, 0x67, 0x27, 0x29, 0x60, 0xdc, 0x1b, 0x6a, 0x24, 0x03, 0x6e, 0x9b, 0xe6, 0x54, 0x36,
	0x11, 0xb6, 0xc3, 0xb0, 0x18, 0x51, 0x16, 0x04, 0x89, 0x89, 0x9d, 0x6d, 0x98, 0xa9, 0xa2, 0x35,
	0xaa, 0xa7, 0xb0, 0x79, 0xcf, 0x71, 0xb4, 0xd8, 0xc4, 0xeb, 0x8b, 0xbf, 0xcd, 0x50, 0x8e, 0xa9,
	0x1c, 0xb0, 0x50, 0xc6, 0xe1, 0x15, 0x36, 0xc4, 0xa2, 0x5f, 0x36, 0x79, 0xb4, 0x10, 0x79, 0x04,
	0x5b, 0xb1, 0xa4, 0xf8, 0x45, 0x6d, 0x07, 0x6f, 0xdb, 0x7f, 0xaa, 0xb1, 0xec, 0x19, 0x34, 0x1d,
	0xba, 0x4d, 0xa8, 0x84, 0xa2, 0xb9, 0x2e, 0xe5, 0x22, 0xab, 0x22, 0x54, 0x7f, 0x8a, 0x91, 0xef,
	0xa0, 0x3a, 0x4a, 0xf8, 0x44, 0xc8, 0xb1, 0xc2, 0xee, 0x65, 0xbb, 0xe5, 0x3c, 0x68, 0x82, 0x16,
	0xb2, 0x38, 0x88, 0x58, 0x72, 0x81, 0x21, 0x21, 0x69, 0xd0, 0xf2, 0xd8, 0x93, 0xbf, 0xad, 0x40,
	0xa5, 0xd3, 0xec, 0xd3, 0xe9, 0x14, 0x54, 0x86, 0x8d, 0x98, 0x6b, 0xf3, 0x2d, 0xec, 0x7e, 0x41,
	0x08, 0x6c, 0x1a, 0x61, 0xf6, 0xb1, 0xea, 0x3a, 0xe4, 0x2b, 0xd8, 0x31, 0xd8, 0xc2, 0xd7, 0xb1,
	0xbb, 0x4a, 0x2a, 0x50, 0x34, 0x0a, 0xd3, 0x6a, 0xdc, 0x35, 0xb2, 0x0d, 0x55, 0xa4, 0x65, 0xdf,
	0x4b, 0x6e, 0x61, 0x0a, 0x65, 0xdf, 0x44, 0xee, 0x3a, 0xd9, 0x81, 0x2d, 0x84, 0x66, 0x5f, 0x2f,
	0xee, 0xc6, 0x6c, 0x85, 0xb9, 0x0b, 0xeb, 0x16, 0xc9, 0x7d, 0xf8, 0x76, 0x41, 0x31, 0xdf, 0x94,
	0xdd, 0x12, 0xf1, 0xe0, 0xee, 0x02, 0x65, 0xa1, 0x0b, 0xba, 0x65, 0x72, 0x07, 0xbe, 0x5c, 0xe0,
	0xa4, 0xdd, 0xc8, 0xad, 0x90, 0x3d, 0xf8, 0x66, 0xc9, 0xd2, 0xd3, 0x5e, 0xe1, 0x56, 0x9f, 0xfc,
	0x73, 0x05, 0xb6, 0x67, 0xea, 0x17, 0xa6, 0x07, 0x51, 0x4d, 0x1e, 0xc3, 0x83, 0xde, 0x69, 0xfd,
	0x6d, 0x87, 0xbe, 0xf4, 0xbb, 0x67, 0xa7, 0xb4, 0xdd, 0xad, 0x1f, 0xd3, 0x66, 0xa7, 0xdf, 0xea,
	0xb7, 0x9a, 0x3d, 0xfa, 0xc2, 0xef, 0x9e, 0xd0, 0x5e, 0xfd, 0x4d, 0xd3, 0x75, 0xc8, 0x03, 0xb8,
	0x97, 0x27, 0x1e, 0x77, 0x3b, 0x7d, 0x9a, 0x02, 0x19, 0xdd, 0x5d, 0x31, 0xe7, 0xcc, 0x93, 0x7a,
	0xef, 0x3a, 0x8d, 0x57, 0x7e, 0xb7, 0xd3, 0x3d, 0xeb, 0xa5, 0x5c, 0x77, 0x8d, 0x3c, 0x02, 0x2f,
	0x4f, 0x69, 0xf5, 0x68, 0xab, 0xd3, 0xea, 0xb7, 0xea, 0x6d, 0x9a, 0x83, 0xdd, 0x22, 0xf9, 0x3f,
	0x78, 0x9c, 0xe7, 0x35, 0xfc, 0x66, 0xbd, 0xdf, 0xa4, 0x8d, 0x76, 0xab, 0xd9, 0xe9, 0xd3, 0x6e,
	0xa7, 0xfd, 0x6e, 0xb6, 0xae, 0x6b, 0x82, 0x97, 0x27, 0x1f, 0xb5, 0xbb, 0x8d, 0xd7, 0xf4, 0xac,
	0xd3, 0x6f, 0xb5, 0xf1, 0x44, 0xcd, 0x63, 0xf7, 0x27, 0xf2, 0xdd, 0xfc, 0x01, 0xf0, 0xa4, 0xbd,
	0xbe, 0xdf, 0xac, 0x9f, 0xb4, 0x3a, 0x2f, 0xe9, 0x71, 0xbd, 0x5f, 0x77, 0x3f, 0x39, 0xe4, 0xf1,
	0xfc, 0xf6, 0xec, 0xb2, 0x9d, 0xe6, 0x5b, 0xda, 0x6b, 0x34, 0x3b, 0x4d, 0xfa, 0xb6, 0xeb, 0xb7,
	0x8f, 0xdd, 0x4f, 0x2b, 0x47, 0xab, 0x9f, 0x9c, 0x2f, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa9,
	0xc1, 0xc6, 0x60, 0xe9, 0x13, 0x00, 0x00,
}
